### ISSUE TITLE
Add Crash Course link at the end of the `Erlang Interoperability` lesson?

### ISSUE THREAD

**Issue by code-shoily** [elixirschool/elixirschool#1010]
There is a great comparison between `Erlang` and `Elixir` syntaxes [here](http://elixir-lang.org/crash-course.html) in the official site. I was thinking maybe we could add a reference to this link in `erlang.md` as a "Note"?

**Comment by doomspork** [comment]
I'm going to close this since it's been almost a year.  @code-shoily if you'd like to make the change a PR would be welcomed 👍
