### ISSUE TITLE
OTP Supervisors section needs clarification

### ISSUE THREAD

**Issue by ChuckIrvine** [elixirschool/elixirschool#1029]
To preface things, I really like your "Elixir School". Nice simple examples. I despise having to wade though someone's very complex example to get to the gist of what is being explained. Thanks!!!

Goto:
https://elixirschool.com/lessons/advanced/otp-supervisors/

The context for the code snippet below is unclear to me. Where should it be placed in the code for SimpleQueue

###########
import Supervisor.Spec
children = [
  worker(SimpleQueue, [], [name: SimpleQueue])
]
{:ok, pid} = Supervisor.start_link(children, strategy: :one_for_one)
############

**Comment by doomspork** [comment]
@ChuckIrvine thanks for reaching out!  You're right, this is unclear and something we should improve.  Were you able to find the answer you needed?

**Comment by 9mm** [comment]
I'd like to add to this that it looks like the syntax for doing a proper supervisor changed after 1.5, and the method mentioned in this whole section is deprecated (anything with `import Supervisor.Spec` if I'm not mistaken).

I'm super confused trying to find a new/good example that isn't this really complicated docs page...https://hexdocs.pm/elixir/master/Supervisor.html

**Comment by chuckhousley** [comment]
The Ecto page also uses the Supervisor.Spec module.  Should the examples be rewritten completely or should there be code snippets for pre-v1.5 like in the [ecto docs](https://github.com/elixir-ecto/ecto/blob/master/guides/Getting%20Started.md#adding-ecto-to-an-application)?

**Comment by doomspork** [comment]
@9mm and @chuckhousley we should update the code to reflect the newer syntax. Would one of you like to take the lead on that?

**Comment by chuckhousley** [comment]
If there are no objections I'd like to take it

**Comment by 9mm** [comment]
@chuckhousley  its all you

**Comment by doomspork** [comment]
Thank you both!

**Comment by notactuallypagemcconnell** [comment]
@chuckhousley @doomspork closing this as the merged PR resolves the issue
