### ISSUE TITLE
[Question] Would you consider using language labels

### ISSUE THREAD

**Issue by pragmaticivan** [elixirschool/elixirschool#1032]
Right now it's really manual to find out where it's missing changes/translation for `pt-BR` for example. And I think if there was a way to just use GitHub labels to filter, It would be easier to send a link to someone saying that those tasks have `pt-BR` dependency and need help. Instead depending on manually update a main task/list for that.

**Comment by doomspork** [comment]
@pragmaticivan always welcome suggestions that make life easier for translators and contributors!  

My only concern would be when we have all the language labels assigned, would it be overwhelming?

@nscyclone, @brain-geek, @cizixs, @gemantzu, and others — any thoughts?

**Comment by pragmaticivan** [comment]
I was thinking about removing the label after a PR is merged. 


I have the same concern about having all the labels in one language. But, the trade off seems to be reasonable in order to get a good label filtering system.

**Comment by gemantzu** [comment]
Actually, my take on this (that I didn't find time to tackle) was to make a plugin in Jekyll that after reading all the pages, creates a report page for each translation that has all the info about the status of the language (x lessons missing, y lessons major etc) which would make it so easy to find lessons that need attention.. This way, any translator could just look at this overview page and find quickly where to contribute. Does this sound like a good solution and is it doable with Jekyll?

**Comment by brain-geek** [comment]
@gemantzu 's suggestion has a lot of sense - I've been thinking for this also.

**Comment by pragmaticivan** [comment]
@gemantzu all good with your solution! :D I think that would be better than using tags

**Comment by doomspork** [comment]
@gemantzu I think it's possible with Jekyll, I'm not 100% how though.  @pragmaticivan would you be interested in helping building this out if it suits your needs?

**Comment by nscyclone** [comment]
Sorry for a late reply.
Jekyll-based solution sounds like a good idea to me. Likely, [generators](https://github.com/jekyll/jekyll/blob/0300a7017b8e69d86d267d1e252d561b34906e77/docs/_docs/plugins.md#generators) is the thing we're looking for.

**Comment by doomspork** [comment]
No worries @nscyclone, thanks for taking the time to respond

**Comment by doomspork** [comment]
If we can hash out the feature set for this I think it would be a great opportunity for someone looking for get in their Hacktoberfest contributions.  What do you all think?

**Comment by gemantzu** [comment]
I will take a hit on this.

**Comment by doomspork** [comment]
Closing this since we have the translation report now.  I am open to creating labels if we deem it necessary going forward 👍
