### ISSUE TITLE
Ebook epub generation

### ISSUE THREAD

**Issue by jamesporter** [elixirschool/elixirschool#1039]
I wanted to read Elixir School on my Kindle so created: https://github.com/jamesporter/elixir-school-ebook

Currently it relies on a forked version of an npm library (as `epub-gen` was removing new lines) and various things are hardcoded but seems to work very well as is (for default language, on my Kindle, after using Calibre to convert the epub file)

If there is any general interest in this there are various ways it could be improved. Obviously I would want to generate all the languages/have nice cover(s)/figure out better way of linking to elixir-school project (currently a submodule). Saw some remarks on #523 around ebook generation.

**Comment by ybur-yug** [comment]
This is awesome @jamesporter. 💥 There has definitely been talk of this and its something I know we all _really_ want to do. Going to check it out now and report back!

**Comment by doomspork** [comment]
Great work @jamesporter!  This is definitely something I'd like to get incorporated into the site, across all languages.

The gentleman behind https://github.com/javierbyte/docs2epub/ reached out to me about tackling the ebook generation but he seemingly vanished and no forward progress has been made.

Let me know if there's anything we can do to facilitate making this part of the Jekyll deployment (so new versions are always generated).

**Comment by jamesporter** [comment]
Unfortunately as it uses javascript/node getting it working with Jekyll could be somewhat tricky. (btw Does Elixir School use github pages?)

Support for other languages, cover image, that kind of thing should all be straightforward. And there is probably much better way of getting latest Elixir School version.

**Comment by doomspork** [comment]
@jamesporter Heroku for now.  I have a DO box we could use to listen to webhooks and run a script to generate the ebooks.

**Comment by milmazz** [comment]
@jamesporter @doomspork Shameless plug here, but you can use [BUPE](https://github.com/milmazz/bupe) to generate EPUB documents using Elixir, there is a current [proposal](https://github.com/elixir-lang/elixir-lang.github.com/issues/860) to offer the official Getting Started guides in EPUB format. Let me know what do you think and I can help if you want.

**Comment by doomspork** [comment]
That's awesome @milmazz!  I'm open to evaluating all of our options, thanks for sharing 👍

**Comment by eksperimental** [comment]
Should we close this issue? It's been a year and there is not foreseeable implementation
