### ISSUE TITLE
Translate Plug lesson 1.1.0

### ISSUE THREAD

**Issue by moxley** [elixirschool/elixirschool#1043]
Major revisions have been made to the Plug lesson, in #861 and #1033. Translations need to be created.

## Translation

Translation progress:

- [x] en
- [ ] ru /cc @brain-geek / @nscyclone
- [ ] ko /cc @devleoper
- [ ] jp /cc @3100
- [ ] no /cc @therobinsj
- [ ] pl /cc @Koziolek
- [ ] sk /cc @michalvalasek
- [ ] fr /cc @julienXX
- [ ] cn /cc @cizixs
- [x] es /cc @aleandros / @jonahoffline / @edwinallenz
- [ ] pt /cc @pragmaticivan
- [ ] vi /cc @joneslee85
- [ ] it /cc @lucidstack / @sformisano
- [ ] my /cc @alkaha
- [ ] id /cc @rezaprima

**Comment by edwinallenz** [comment]
While I'm translating this lesson to spanish, I'm also doing the Plug exercise. As I'm doing the section https://github.com/doomspork/elixir-school/blob/master/lessons/specifics/plug.md#adding-another-plug 
I'm getting a 500 response when a POST is performed to the /upload endpoint, and I'm not able to see any error message in the terminal.

Other endpoints as `/` or other are responding well with 200 and 404
This is my repo if you're able to  give it a shot
https://github.com/edwinallenz/plug_lesson

thanks

**Comment by gemantzu** [comment]
Greek #1128
