### ISSUE TITLE
Genstage lesson: Specify `lib/genstage_example/application.ex` in "Putting it all together"

### ISSUE THREAD

**Issue by Ivor** [elixirschool/elixirschool#1126]
I just wanted to follow the example, cutting and pasting as I was reading through the lesson. 

In the putting it all together the instruction is to put the following in `lib/genstage_example.ex`

```
def start(_type, _args) do
  import Supervisor.Spec, warn: false

  children = [
    worker(GenstageExample.Producer, [0]),
    worker(GenstageExample.ProducerConsumer, []),
    worker(GenstageExample.Consumer, []),
  ]

  opts = [strategy: :one_for_one, name: GenstageExample.Supervisor]
  Supervisor.start_link(children, opts)
end
```

This had to go in the `lib/genstage_example/application.ex` for it to work for me. 
If I am doing something wrong I would greatly appreciate feedback, otherwise I think this is a mistake in the lesson?

**Comment by doomspork** [comment]
Howdy @Ivor!  Both are right, sort of.  Prior to Elixir 1.4 the OTP application functionality (like start/2) lived in `lib/project_name.ex`, as of 1.4 this was moved to `lib/project_name/application.ex.  We should update the lessons to better reflect what 1.4 does now that it's been out for awhile.  Hope that helps!

**Comment by Ivor** [comment]
@doomspork thanks for the clarification. I suspected it was a change like that but didn't know. I think it will be good to either update to the the 1.4 way or including both versions. Took me a good while to figure out that following the instructions was not working. It fails *very* silenty. Appreciate the site!

**Comment by doomspork** [comment]
@Ivor I think we should update to 1.4.  Would you like to take a stab at updating the lesson?
