### ISSUE TITLE
(UndefinedFunctionError) function :crypto.rand_bytes/1 is undefined or private

### ISSUE THREAD

**Issue by jaytheking** [elixirschool/elixirschool#1138]
Reading through the Basics guide, there is an older function `:crypto.rand_bytes`. This should be replaced with `:crypto.strong_rand_bytes`.

Otherwise if im wrong please explain what i need to do to get that to work with latest version of elixir and erlang VM.

**Comment by nscyclone** [comment]
Thanks, @jaytheking! You're right and @bguiz is already working on it in #1132.

**Comment by jaytheking** [comment]
@nscyclone Aahh my bad, I did try searching before posting the issue and didn't find that.

**Comment by nscyclone** [comment]
Fixed in #1132. Thanks, @bguiz and @jaytheking!
