### ISSUE TITLE
Producer section in GenStage may need clarification

### ISSUE THREAD

**Issue by picandocodigo** [elixirschool/elixirschool#1163]
The [Producer](https://elixirschool.com/en/lessons/advanced/gen-stage/#producer) section of the GenStage lesson says:
>The `handle_demand/2` function is where the majority of our producer and must be implemented by all GenStage producers.
 
Should it be something like: `where the majority of our producer is defined, and must be implemented...`?

**Comment by nscyclone** [comment]
Great catch, thanks, @picandocodigo! Your suggestion sounds good, but I'd rather split it into two sentences:
>The handle_demand/2 function is where the majority of our producer is defined. It must be implemented by all GenStage producers.

What do you think about this? Would you like to fix this? If you have any questions, feel free to ask, we're always glad to help!

**Comment by picandocodigo** [comment]
Yes, I think it makes sense to split it into two sentences. Would you like me to submit a PR with this fix?

**Comment by nscyclone** [comment]
@picandocodigo Sure, that would be great! Please, don't forget to update the [patch version in the lesson metadata](https://github.com/elixirschool/elixirschool/blame/master/en/lessons/advanced/gen-stage.md#L2). Thanks in advance!
