### ISSUE TITLE
Outdated README.md

### ISSUE THREAD

**Issue by iboss-ptk** [elixirschool/elixirschool#1183]
The translation section is outdated.
1. configuring `url` in `_config.yml` is not needed anymore.
2. language config like `section`, `description` has been extracted to `_data/locales/[language_code].yml` not in `_config.yml` anymore

If such PR is welcome. I'm happy to help :)

**Comment by doomspork** [comment]
@iboss-ptk PR away!  Thanks for getting involved 😁

**Comment by iboss-ptk** [comment]
just curious that why

> if this is an initial lesson translation, the version should be set to 1.0.0

since doing that will make the page warn about outdated content? @doomspork

**Comment by nscyclone** [comment]
@iboss-ptk, you're right, the version should be copied from the original lesson.

**Comment by doomspork** [comment]
@iboss-ptk thank you again for all of your help on the Thai translation and updates to the translating guide.  

Would you be open to joining the Elixir School organization and heading up the Thai translations?  We just ask that you don't push to Master or merge PRs without giving people an opportunity to review them 😀

**Comment by iboss-ptk** [comment]
@doomspork Oh sure I would love to :)

**Comment by doomspork** [comment]
@iboss-ptk invite sent 😀  Thanks again for all your help

**Comment by eksperimental** [comment]
ping
