### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by squaresurf** [elixirschool/elixirschool#1203]
I would love for there to be a favicon so it would be easier to find the elixirschool tabs I have open. Has this been discussed anywhere?

**Comment by doomspork** [comment]
@squaresurf I swore we had this before 🤔 I'd be happy to add one, would you like to open a Pull Request to do so?

**Comment by squaresurf** [comment]
I'd love to open a PR. Is there a logo from which I could build a favicon?

**Comment by doomspork** [comment]
@squaresurf this is the only image I currently have https://github.com/elixirschool/elixirschool/blob/master/_assets/images/og_image.jpg

**Comment by squaresurf** [comment]
I just opened a PR that should accomplish this :smile:.
