### ISSUE TITLE
[KO] Arities of chunk_every/4 section in ko/basic/enum.md seemed wrong

### ISSUE THREAD

**Issue by flavono123** [elixirschool/elixirschool#1256]
Compared to English enum.md in basic, the chunk_every section of it in Korean seemed wrong.

The text of \<h3> tag should be `chunk_every`, not `chunk_every/2` and followed two code pieces of `chunk_every/4` should be `chunk_every/2` and `chunk_every/4` in order, respectively. (The 3rd `chunk_every/4` in Korean enum.md is OK)

[English version](https://elixirschool.com/en/lessons/basics/enum/#chunk_every) is look like this:
<img width="761" alt="enum_ _elixir_school" src="https://user-images.githubusercontent.com/20619567/32710168-7dc4b1b8-c879-11e7-8f2f-8674e3522c93.png">

And [Korean version of that](https://elixirschool.com/ko/lessons/basics/enum/#chunk_every2) is:
<img width="744" alt="enum_ _elixir_school" src="https://user-images.githubusercontent.com/20619567/32710229-db920a34-c879-11e7-888f-5914f5b3ad8a.png">

May I do PR for this?

**Comment by doomspork** [comment]
@flavono123 please do!  We'll have someone on @elixirschool/korean review it for you 😁

**Comment by flavono123** [comment]
@doomspork Thanks! The work is in PR #1257

**Comment by marocchino** [comment]
Some other translations also need to fix title `chunk_every/2` -> `chunk_every`
#1170

**Comment by flavono123** [comment]
@marocchino Checked the list of languages, cn, de, es, fr, gr, it, jp, my, no, pl, pt, ru and vi, except Korean, that the title of `chunk_every` section written in `chunk_every/2`.
I'll PR for this after the Korean version merged.

**Comment by flavono123** [comment]
Closing since #1257 is merged
