### ISSUE TITLE
[TW] Traditional Chinese Translations

### ISSUE THREAD

**Issue by lithiumpie** [elixirschool/elixirschool#1264]
Get Involved!
---
We are seeking **Traditional Chinese** translators for this project. If you would like to get involved with translating a lesson. Please folk the project and start translating.

- Set up
  - [x] _config.yml
  - [x] index.md

- Basics
  - [x] Basics
  - [x] Collections
  - [x] Enum
  - [x] Pattern Matching
  - [x] Control Structures
  - [x] Functions
  - [x] Pipe Operator
  - [x] Modules
  - [x] Mix
  - [x] Sigils
  - [x] Documentation
  - [x] Testing
  - [x] Comprehensions
  - [x] Strings
  - [x] Custom Mix Tasks
  - [x] IEx Helpers

- Advanced
  - [x] Erlang Interoperability
  - [x] Error Handling
  - [x] Executables
  - [x] Concurrency
  - [x] OTP Concurrency
  - [x] OTP Supervisors
  - [x] Metaprogramming
  - [x] Umbrella Projects
  - [x] Specifications and types
  - [x] Behaviours
  - [x] GenStage
  - [x] Protocols

- Specifics
  - [ ] Plug
  - [ ] Ecto
  - [ ] Embedded Elixir (EEx)
  - [ ] Erlang Term Storage (ETS)
  - [ ] Mnesia
  - [ ] Debugging

- Libraries
  - [ ] Guardian (Basics)
  - [ ] Poolboy
  - [ ] Benchee

**Note**
Those new to Elixir and / or Github are encouraged to get involved :smile:. 1 [Pull Request](https://help.github.com/articles/about-pull-requests/) per lesson.

**Comment by lithiumpie** [comment]
#1263 Initial zh-tw translation @cizixs @yuchunc @taiansu

**Comment by doomspork** [comment]
This is wonderful!  Thank you @lithiumpie.  Let me know if there's anything you need help with 😁

**Comment by lithiumpie** [comment]
#1285 [TW] Translation Finish of Basics Section @doomspork @cizixs 
Happy New Year 2018 & Merry Christmas, Amigo.
After this PR, All Basics Lessons are completed.

**Comment by eksperimental** [comment]
TW is not a valid language code. I highly suggest to use zh-tw as the code, and rename and move to a zh-tw dir

**Comment by eksperimental** [comment]
We may also want to add to instructions that when adding a.new language extract the language code from a link, maybe a wikipedia article.

**Comment by lithiumpie** [comment]
@doomspork @cizixs 
I agree to use the specific language code, zh-tw. The reason that I choose TW because only 2 characters were named for language code before.

**Comment by doomspork** [comment]
Thank you @eksperimental and @lithiumpie.  I'm just getting back from my holiday so I'll look into updating the language codes this week 👍

**Comment by lithiumpie** [comment]
@doomspork @cizixs 
Advanced lessons Translation from 1.erlang to 12.protocols.
#1384
