### ISSUE TITLE
Suggestion for Process Linking lesson

### ISSUE THREAD

**Issue by picandocodigo** [elixirschool/elixirschool#1276]
Reading through [Process Linking](https://elixirschool.com/en/lessons/advanced/concurrency/#process-linking), I found the example code about trapping the exits confusing at first. I didn't know if `:trap_exit` was being defined or was a standard Elixir thing or something else. I did some reading on Elixir's documentation, and maybe this is what the lessons are trying to encourage (there's nothing wrong with that), but it sounds like it could be more clear changing the text for something like this:

>Sometimes we don’t want our linked process to crash the current one. For that we need to trap the exits. To trap the exits, we use the `Process` module's `flag/2` function. This module uses [erlang's `process_flag` function](http://erlang.org/doc/man/erlang.html#process_flag-2) for the `trap_exit` flag. When trapping exits (`trap_exit` is set to `true`), exit signals will be received as a tuple message: `{:EXIT, from_pid, reason}`.

**Comment by doomspork** [comment]
@picandocodigo would you please open a PR with this change?

**Comment by picandocodigo** [comment]
@doomspork done! 🤘
