### ISSUE TITLE
Language defaults to "tw" on Safari/Webkit Browsers

### ISSUE THREAD

**Issue by nsuchy** [elixirschool/elixirschool#1282]
When loading ElixirSchool directly from https://elixirschool.com/ I'm always redirected to https://elixirschool.com/tw/, I've cleared cookies/cache to ensure this isn't a me issue. Thoughts?

**Comment by mikey0000** [comment]
seconding, happening to me on Firefox linux. [en-GB, en, en-NZ]

**Comment by nscyclone** [comment]
Thanks for the report, I think that #1286 should fix the issue. Merry Christmas!

**Comment by eksperimental** [comment]
@nscyclone this issues goes deeper thah this, i see many TW and at least a TR lesson that left the redirect_from info from the English version lessons. I think a comment must be added to remove that directive when translating lessons, and all redirects in recently translated lessons should be removed ASAP.
Additionaly if we are using a continuous integration system, a check should be added somehow so no two or more pages use the same redirect from

**Comment by nscyclone** [comment]
Great point, thanks, @eksperimental! I've updated #1286 recently.

**Comment by eksperimental** [comment]
Looks great. By adding a comment i mean to add it to every single English lesson that uses redirectfrom. People translating new lessons of an exisiting language are not likely to read the cobtributing file,  so i would recommend them

**Comment by eksperimental** [comment]
(oops. Hit the wrong button)
So i would recommend to include it in every lesson

**Comment by eksperimental** [comment]
Another solution will be to use a direfent way of redirecting, maybe a different plug-in which allows us to set all redirects in one file therefore removing the noise from all the english lessons.

Regardless the path we choose I would remove the redirect_from directive in en/index.md and create /index.md with a redirect_to pointing to en/index.md. sin e this is a  very imoortant page i think it iz better to be explicit here than let users figure out how the redirection is working

**Comment by lithiumpie** [comment]
Same here. I do translation with my local files and check the output locally. I thought that just my system's problem in the first. I will remove every redirect_form my last PR. I am new to Rails and Jekyll framework so I do not know that what it will cause. :innocent:

**Comment by doomspork** [comment]
I'm working with @burden on a new layout for the site and I'd like to improve the flow of things as part of that.  I for one don't really like that going to www.elixirschool.com redirects you to www.elixirschool.com/en, I think there's a better solution out there.  We just need to find it 😁

**Comment by eksperimental** [comment]
I don't think the issue has been solved completely, i would leave it open or create a new issue regarding the issue with redirect-from
