### ISSUE TITLE
Translations Update `ko/lessons/advanced/concurrency.md`.

### ISSUE THREAD

**Issue by jhsbeat** [elixirschool/elixirschool#1284]
PR #1283 molded some sentences to clear explanation for spawn linkage on concurrency chapter. 

## Translation
Translation progress:

- [x] ko /cc @devleoper 

Other languages don't need to follow the progress.

**Comment by devleoper** [comment]
참여해 주셔서 감사합니다! 이슈 트래킹에는 영어판에서 추가되거나 변경된 레슨을 다른 언어에 적용하거나 한 언어를 새로 번역하는 것처럼 긴 프로젝트를 기록하고 새로 오시는 분들이 찾기 쉽도록 하는 목적이 큰 것 같아서 PR 하나는 바로 @elixirschool/korean 을 멘션해주시면 리뷰하고 머지할 때 조금 편안하실 거예요. 아무튼 감사합니다!

tl;dr: Anyway, thank you for countributing to make Korean translation better! :tada:
