### ISSUE TITLE
[PT] Keep up with current state for Portuguese

### ISSUE THREAD

**Issue by pragmaticivan** [elixirschool/elixirschool#1295]
met## Básico
- [x] Básico
- [x] Coleções
- [x] Enum - @pragmaticivan
- [x] Pattern Matching - @brunoliveira8
- [x] Estruturas de Controle - @pedrosnk
- [x] Funções - @jrichocean ~~#1302~~
- [x] Operador Pipe - @jrichocean ~~#1302~~
- [ ] Composição - @pedrosnk #1300
- [x] Mix - @pedrosnk ~~#1301~~ 
- [ ] Sigils - @jrichocean
- [ ] Documentação - @jrichocean
- [ ] Testando - @renatosuero
- [x] Comprehensions - @thiamsantos 
- [ ] Strings - @brunoliveira8
- [x] Tarefas Mix Customizadas - @brunoliveira8 ~~#1321~~
- [x] IEx Helpers

## Avançado
- [ ] Interoperabilidade com Erlang - @mememori
- [x] Tratamento de Erros
- [x] Executáveis - @thiamsantos 
- [ ] Concorrência - @mememori
- [ ] Concorrência OTP - @mememori
- [ ] Supervisores OTP - @mememori
- [x] Metaprogramação - @thiamsantos
- [x] Projetos Guarda-chuva
- [x] Especificações e tipos
- [x] Comportamentos
- [x] GenStage
- [x] Protocols

## Específico
- [x] Plug
- [ ] Ecto - @mememori
- [ ] Elixir embutido (EEx) - @renatosuero
- [ ] Erlang Term Storage (ETS) - @mememori
- [x] Mnesia - @thiamsantos
- [x] Debugging

## Biblioteca
- [x] Guardian (Basics)
- [ ] Poolboy - @mememori
- [x] Benchee
- [x] Bypass

**Comment by pragmaticivan** [comment]
basic - enum (https://github.com/elixirschool/elixirschool/pull/1297/files)

**Comment by brunoliveira8** [comment]
basic - pattern matching (https://github.com/elixirschool/elixirschool/pull/1298)

**Comment by pedrosnk** [comment]
basic - Estruturas de Controle

**Comment by doomspork** [comment]
Thank you @pragmaticivan, @brunoliveira8, @pedrosnk for helping ❤️

**Comment by jrichocean** [comment]
I can do basic - pipe operator & functions

**Comment by doomspork** [comment]
That would be wonderful @jrichocean 😁

**Comment by mememori** [comment]
I can translate:

- Interoperabilidade com Erlang
- Concorrência
- Concorrência OTP
- Supervisores OTP
- Ecto
- Erlang Term Storage (ETS)
- Poolboy

Bind them to me, i'll take a look at those in the following weeks

**Comment by pragmaticivan** [comment]
That's cool! Thanks @mememori !

**Comment by renatosuero** [comment]
I can do Testando

**Comment by pragmaticivan** [comment]
Thanks @renatosuero !

**Comment by jrichocean** [comment]
I can do Basic: Sigils, Composition, and Documentation.

**Comment by brunoliveira8** [comment]
Mix is updated. https://github.com/elixirschool/elixirschool/pull/1301

**Comment by brunoliveira8** [comment]
I can do Basic: Strings and Tarefas Mix Customizadas.

**Comment by renatosuero** [comment]
I will do Specifics Eex

**Comment by pragmaticivan** [comment]
Nice, thanks @renatosuero !

**Comment by thiamsantos** [comment]
advanced - metaprogramming #1306

**Comment by renatosuero** [comment]
The link https://elixirschool.com/pt/lessons/specifics/eex/ has a problem, eternal redirect.

**Comment by brunoliveira8** [comment]
basics - mix tasks https://github.com/elixirschool/elixirschool/pull/1321

**Comment by eksperimental** [comment]
I have just renamed the title of the issue from PT-BR to just PT

**Comment by thiamsantos** [comment]
basic - comprehensions #1338

**Comment by thiamsantos** [comment]
advanced - escripts #1339

**Comment by thiamsantos** [comment]
specifics - mnesia #1340

**Comment by thiamsantos** [comment]
advanced - umbrella projects #1381

**Comment by thiamsantos** [comment]
libraries - guardian #1383
