### ISSUE TITLE
Exercises

### ISSUE THREAD

**Issue by gemantzu** [elixirschool/elixirschool#1310]
How would you all like the idea of adding some exercises in each lesson? I feel that without them we are somewhat incomplete as a `school`. I don't think we should include the answers though, this would add some value to the slack channel ;)

**Comment by arjun289** [comment]
Building that would take quite some time. It would be cool if it's linked to [`exercism.io`](http://exercism.io) for now. Just a suggestion.

**Comment by doomspork** [comment]
@gemantzu I would love to add exercises without linking out to external sites. A couple of things we could do:

+ Continue to add exercises like we did in the String lesson: https://elixirschool.com/en/lessons/basics/strings#exercises
+ Evaluate something like Elixir Playground or other in-browser solutions.

In addition to individual lesson exercises I want to look at a whole new section: Basics, Advanced, Specifics, Libraries, *Projects*.  Projects would be full fledged tutorials (more involved than our current lessons) that walk you through building simple applications in Elixir.

Thoughts?

**Comment by gemantzu** [comment]
That's exactly what I think. We should not have to leave the site to do some exercises, after all exercism is a solution that is usefull after you have learned quite a lot of the language, not something you can do after reading on a specific topic of elixirschool. I don't know about in-browser solutions, how can something like this be integrated with jekyll?

Also, projects section cannot come soon enough :) Is it OK if I make an issue and start building a skeleton with what I think is needed so we can start working on it?

**Comment by doomspork** [comment]
@gemantzu do you want to move ahead with this?

**Comment by gemantzu** [comment]
Yes I do, please review my efforts when I am done :)

**Comment by doomspork** [comment]
Wonderful @gemantzu!  I started on something last night I'm anxious to share with you.  I will hopefully wrap it up today or early this week 👍

**Comment by doomspork** [comment]
@gemantzu please help! 😁 

Open issues for new challenges so we can discuss them 👍
