### ISSUE TITLE
Correct language code for Chinese/Mandarin translation

### ISSUE THREAD

**Issue by eksperimental** [elixirschool/elixirschool#1366]
cn is the code for CHINA, but not for the language. Zh is.
I am not sure if we should go with a code for traditional and simplified chinese, instead of one that represent the countries such as zh-CN and zh-TW as these languages are used outside of Taiwan and mainland China

**Comment by burden** [comment]
Went ahead and removed :cn in the PR for now. 

@doomspork do you have any input on the sample code for the front page? was it simplified or traditional?

**Comment by doomspork** [comment]
I'm 80% sure it's simplified.  The traditional stuff came much later.

**Comment by eksperimental** [comment]
We should go with `zh-Hans` for Simplified Chinese (currently `cn`) and with `za-Hant` for Traditional Chinese (currently `tw`) if we want to be correct about the codes 

source: https://stackoverflow.com/questions/4892372/language-codes-for-simplified-chinese-and-traditional-chinese

**Comment by doomspork** [comment]
@eksperimental PR #1423 has that change 👍

**Comment by nscyclone** [comment]
Reslolved in #1423.
