### ISSUE TITLE
Broken images links

### ISSUE THREAD

**Issue by BEaStia** [elixirschool/elixirschool#1386]
Hello! I've found that some image links are broken and tried to fix it in [PR](https://github.com/elixirschool/elixirschool/pull/1385)

In English version in `debugging` section there're some screenshots:
<img width="788" alt="2018-04-06 9 18 51" src="https://user-images.githubusercontent.com/2078466/38406003-a70f73aa-397b-11e8-9e64-335dde4085d1.png">

But in Russian version they look like:
<img width="787" alt="2018-04-06 9 20 11" src="https://user-images.githubusercontent.com/2078466/38406015-bc6314d2-397b-11e8-8a6c-ee8fd9a4b983.png">

**Comment by doomspork** [comment]
Thank you for taking the initiative to fix this @BEaStia 😁
