### ISSUE TITLE
Tracking translation changes

### ISSUE THREAD

**Issue by doomspork** [elixirschool/elixirschool#1424]
This doesn't need to be a lengthy conversation, I'd like to get a quick poll on how useful folks find these Issues given the versioning system we have in place:

- https://github.com/elixirschool/elixirschool/issues/956
- https://github.com/elixirschool/elixirschool/issues/947
- https://github.com/elixirschool/elixirschool/issues/922
- https://github.com/elixirschool/elixirschool/issues/921
- https://github.com/elixirschool/elixirschool/issues/920

**Comment by eksperimental** [comment]
I think they are useful when a new language is starting and you need help, and visibility.
I think it's a pain on the neck to have one issue of this for every update on the lessons.

The thing is that, for the time being, there are no other methods to let people now about the updates

**Comment by nscyclone** [comment]
They are pretty useful for translating to a new language for preventing people from doing the same work twice. But it doesn't look like issues with the recent changes waiting for translations do their work. There are a lot of them hanging for a long time without any serious progress.
In my opinion, the versioning system seems sufficient for finding out _what has become outdated_, but unfortunately it doesn't answer the question "_what exactly has changed?_". It would be really great if we could somehow answer it to make catching up process easier and friendlier.

**Comment by doomspork** [comment]
With plugs and versioning I feel like we should be able to generate some sort of report on what lessons are out-of-date and maybe even attempt to diff the English lesson between that version and the current?

**Comment by gemantzu** [comment]
I tried to solve this a while back. My thought at the time was to make a report in the homepage of each translation on what needed attention. But I lost track of what I was doing due to heavy work load at the time and it stagnated. Is this what you are talking about?

**Comment by doomspork** [comment]
Now that the translation report has been rolled out how do you folks feel about closing the existing issues?
