### ISSUE TITLE
Should version severity captions in translation reports be translated?

### ISSUE THREAD

**Issue by nscyclone** [elixirschool/elixirschool#1452]
The question is pretty simple:

<details>
<summary>should this</summary>

![current](https://user-images.githubusercontent.com/5345029/40549873-45851a94-6041-11e8-89f5-592def59b981.png)

</details>

<details>
<summary>look this way?</summary>

_using an existing translation for different severity levels:_

![proposed_translated](https://user-images.githubusercontent.com/5345029/40549966-8264cdec-6041-11e8-9c3f-8ec92b5da519.png)

_falling back to English when translation is not available yet:_

![proposed_default](https://user-images.githubusercontent.com/5345029/40549891-4fbd4054-6041-11e8-997a-6996a58286bf.png)

</details>

Detailed explanation makes more sense than a single word, but repeating descriptions may take a lot of space. WDYT?

**Comment by eksperimental** [comment]
+1 with detailed.
Plus having patch, none, minor, major in English makes no sense in other languages

**Comment by gemantzu** [comment]
To be honest with you, I don't like either of these. I think as @eksperimental said, it makes no sense for translations now as it is, but if we make it full text it will be cluttered with text that's pretty much the same. I guess I would like it better if there was only the bullet, which on mouse over would have the text shown. What do you think?

**Comment by doomspork** [comment]
I'm 💯 onboard with this change @nscyclone!  Let's do it 👍

**Comment by nscyclone** [comment]
@gemantzu I considered your approach before and I find it a good option. Once the meaning of the bullet color is known, there is no sense to constantly see repeating description next to it.
Previous changes were merged already so I've proposed a new PR (#1455) that implements aforementioned approach .

**Comment by gemantzu** [comment]
I will check it out when I get back from work :)
