### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by sotojuan** [elixirschool/elixirschool#1465]
Would be great to add a toggle for a dark theme. I'm not a designer not good with colors but would be happy to implement the actual toggle button and behavior.

**Comment by doomspork** [comment]
Hello @sotojuan!  This is something I think a great deal of people would love to have.  @burden and myself have discussed this a bit but have never come to a consensus on approach.  If you have any thoughts or could point us towards any projects you think might be useful, that would be tremendously helpful!

**Comment by nscyclone** [comment]
Thanks to everyone involved into this! The dark theme looks really cool.
I suppose that the issue can be closed since all the changes are already available.
