### ISSUE TITLE
Whitelist Tor on Cloudflare?

### ISSUE THREAD

**Issue by nsuchy** [elixirschool/elixirschool#1467]
When accessing the site from Tor I am constantly captch-ed. Would the project consider whitelisting Tor traffic or at least switching to the "Javascript Captcha" instead?

**Comment by burden** [comment]
We'll see about getting that worked out. Thanks for the heads up @nsuchy.

**Comment by doomspork** [comment]
@nsuchy it should be done, can you let me know?

**Comment by nsuchy** [comment]
<img width="1280" alt="screen shot 2018-07-06 at 10 55 07 am" src="https://user-images.githubusercontent.com/8227641/42385547-14476a32-810b-11e8-86f4-c6c1cfc7118c.png">
Works for me 😄 Thank you for resolving that ❤️
