### ISSUE TITLE
Language code conflict (my: "ms")

### ISSUE THREAD

**Issue by sawthinkar** [elixirschool/elixirschool#1468]
Language code conflict in _data/redirects.yml.
According to the list in https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes, 'my' is for Burmese and 'ms' is for Malay.

**Comment by doomspork** [comment]
@sawthinkar this is intentional due to a previous mistake with these codes.  Are you trying to contribute the Burmese lessons?

**Comment by sawthinkar** [comment]
Yes, I am. Thanks.

**Comment by doomspork** [comment]
@sawthinkar when you make your first commit we can remove the redirect 👍
