### ISSUE TITLE
Include the current state of `_data/locales` in translation reports

### ISSUE THREAD

**Issue by nscyclone** [elixirschool/elixirschool#1476]
[`interlang`](https://github.com/elixirschool/elixirschool/blob/master/_data/interlang.yml) is a file containing translated language names that are used as [`title` for language links in the sidebar](https://github.com/elixirschool/elixirschool/blob/master/_includes/section-sidebar-langs.html#L6-L15). Currently we've no information about it anywhere so it remains unmaintained for a long period of time. At the moment there are only 5 out of more than 20 translations available. I suppose that one of the most straightforward ways to encourage progress on this is including it in translation reports. But the problem is that `interlang` is not a lesson so it doesn't really fit into the current table format with versions, names and other related stuff. 

WDYT, @elixirschool/developers?

**Comment by gemantzu** [comment]
Hm, would it be sensible to put the content in the locales/lang.yml?

**Comment by nscyclone** [comment]
Sorry for a late reply, @gemantzu.
I found your idea really great. Please take a look at #1488.
Actually it's not about `interlang` only, translation reports don't yet provide any infromation about `locales` as well. When all the configuration related to translation will be in a single file per language would be great to find a way to track its state in the report.

**Comment by gemantzu** [comment]
This is really good actually, all translation specific in one place. 👍 
Regarding the locales files, I think that currently what we do might be sufficient enough for now (enforcing that all locale files are the same, I have been forced to do that from other ppl in ES in the past).
@doomspork your opinion?

**Comment by doomspork** [comment]
@gemantzu / @nscyclone I'm on board!  I merged #1488 👍

**Comment by eksperimental** [comment]
Please follow the discussion there as i have raised a concern
