### ISSUE TITLE
Ecto cast/4 misused

### ISSUE THREAD

**Issue by Hugo-Hache** [elixirschool/elixirschool#1481]
The Ecto lesson tells that 

> we use cast/4 to convert our parameters to a changeset from a set of required and optional fields

 and in examples uses it like this 

`|> cast(params, @required_fields, @optional_fields)`

However ecto/4 [documentation](https://hexdocs.pm/ecto/Ecto.Changeset.html#cast/4) refers the third parameter as permitted and the last as options. So I suppose the lesson should use it like this:

```
|> cast(params, @required_fields ++ @optional_fields)
|> validate_required(@required_fields)
```

**Comment by doomspork** [comment]
@Hugo-Hache good catch, Ecto has changed since the lesson was written.  Would you be open to submitting a PR to update it?
