### ISSUE TITLE
New Content: Phoenix, Ecto, and OTP

### ISSUE THREAD

**Issue by doomspork** [elixirschool/elixirschool#1491]
I'd like to begin expanding the lessons here to include three new categories: Phoenix, Ecto, and OTP.  We will relocate existing lessons to these sections where appropriate.

Some of the content we could cover in these lessons:

- Phoenix
  - [ ] SPA + API
  - [ ] Websockets
  - [ ] Application architecture
- Ecto
  - [ ] Getting started (re-purpose existing lesson)
  - [ ] Associations
- OTP
  - [ ] Application design
  - [ ] Distribution

Thoughts @gemantzu, @willykaram, and @elixirschool/developers?

**Comment by gemantzu** [comment]
Here are my thoughts: 
1. Add a Nerves category (this is something I want to work on, so I will try and research for some lessons)
2. Phoenix: some stuff out of the top of my head - Getting started, Contexts, Plug (repurpose lesson), Presence, Channels, Assets (webpack now that Phoenix is heading that way).
3. Ecto will need some more love as well, but we will figure them as we go.

**Comment by svileng** [comment]
Hi all — I'm the author of [A brief guide to Ecto.Multi](https://medium.com/heresy-dev/a-brief-guide-to-ecto-multi-9c8ea0c729f0). I thought it might be a good fit for the ElixirSchool blog or a sub-section for Ecto if the language is changed a bit to match the existing style.

What do you think? I'd be happy to work on the updated version and submit a draft if there's interest.
