### ISSUE TITLE
New Ecto Section & Lessons

### ISSUE THREAD

**Issue by doomspork** [elixirschool/elixirschool#1519]
After many requests we've decided to proceed with a section dedicated to Ecto, going above and beyond our existing lessons.

Here are the current lessons and subsections we've come up with, these are fluid and open to discussion.  Ideally each lessons equates to a single PR so others may participate.

_New!_ __Ecto Section__

- [x] Basics (lesson)
  - What is Ecto?
  - What isn’t Ecto?
  - Overview of adapters
  - Working with Ecto
  - Migrations
  - Schemas
- [x] Associations
  - Belongs to
  - Has many
  - Many to Many
  - Saving associations
  - Retrieving associated data
    - Preload etc 
- [x] Changesets
  - Basic changeset usage
  - Look at validation
  - Custom validations
  - Changeset design approaches
    - `changeset/2` vs `create_changeset/1` & `update_changeset/2`
- [x] Querying Data
  - Essentials of from/belongs to/where
  - Changesets and not having to touch the database
  - DSL vs functions
  - SQL functions (basics, a la count)
  - More in-depth association querying
- [ ] Advanced Querying
  - Complex joins
  - Fragments
  - Ecto.Multi
- [ ] Query Composition
  - Piped querying
  - Functional approach
  - Comparison

**Comment by gj** [comment]
@doomspork to start, I'll split the Querying Data / Advanced Querying lessons with @notactuallypagemcconnell

**Comment by jeremyjung** [comment]
I can take the basics section.

**Comment by svileng** [comment]
I suspect it won't be much work for me to re-se my [short article on Ecto.Multi](https://medium.com/heresy-dev/a-brief-guide-to-ecto-multi-9c8ea0c729f0), just need to re-read it once again, make any changes if necessary and open a PR. Feel free to ping me if you don't see a PR by end of next week :)

A suggestion for the `Associations` chapter: working with embedded schemas. I remember I struggled a bit when I started using embedded schemas, not just setting them up, but also when updating & replacing `embeds_many` relationships. If no one picks that up, I can definitely write something up, but I'm a bit short on time, so not sure when that would happen 😞

**Comment by doomspork** [comment]
@jeremyjung I think we can re-use some of our existing lesson and then delete it once yours is ready.  The new Ecto section will replace the single Ecto lesson by expanding on the content.

> A suggestion for the Associations chapter: working with embedded schemas. I remember I struggled a bit when I started using embedded schemas, not just setting them up, but also when updating & replacing embeds_many relationships.

@svileng this is a great idea!  I've heard this same concern/confusion/issues from others.  Covering that would be awesome.  @notactuallypagemcconnell we briefly touched on this yesterday, would this be a section you and your co-workers were keen to cover?

**Comment by notactuallypagemcconnell** [comment]
@doomspork I believe we can handle 'Querying Data' and 'Advanced Querying', then leave the rest up for grabs.

**Comment by SophieDeBenedetto** [comment]
@doomspork I'd be happy to take the associations section if its still up for grabs

**Comment by svileng** [comment]
What do you think about moving the `Ecto.Multi` content from `Advanced Querying` to `Query Composition`? It's an odd one, since you can use for querying as well as create/update/delete or a mix of all of them.

**Comment by doomspork** [comment]
@svileng that's a good point, I think we should do that.  Thank you! 👍

**Comment by svileng** [comment]
Right, I'd like to reserve the `Changesets` chapter, expecting to begin work on it this weekend ✌️

**Comment by notactuallypagemcconnell** [comment]
@svileng that is fine by me, I dont have a plan to conquer that one. If anyone else chimes in maybe we could let a newcomer grab it, but otherwise definitely 👍 from me. Though with Hacktoberfest ending, I feel like chances are low we'll get another new person. It generally falls off pretty quickly after October.

**Comment by svileng** [comment]
No probs, happy for someone else to take ownership 👍

**Comment by doomspork** [comment]
@svileng thank you so much for all of your help with this stuff.  I _really really_ appreciate all of y'all's help with these lessons and updates! 😁

**Comment by SophieDeBenedetto** [comment]
@notactuallypagemcconnell @gj, I'm looking back over my draft and breaking out the querying section so you guys can include in your section. Feel like we should re-order this unit a bit: 

1. Basics
2. Changesets
3. Associations
4. Querying

Inserting associated data requires some basic knowledge of changesets in my opinion and my draft reflects that. Added advantage of such a reordering is that we can segue really nicely from associations section into querying section, starting with querying for records and associated records (i.e. the section we'll moving from Associations into Querying). 

If we feel strongly that original order outlined in this issue is best, I can add something like: "We'll learn more about changesets in the following section, etc".

**Comment by SophieDeBenedetto** [comment]
Update:
* Associations lesson PR is ready to go #1553 
* Querying lesson will include content on querying assocaited records, formerly included in Associations lesson. That content has been removed from Associations lesson and placed in a WIP PR for Querying lesson for @notactuallypagemcconnell and @gj to use here #1610
