### ISSUE TITLE
Question about licensing / copyrights

### ISSUE THREAD

**Issue by svileng** [elixirschool/elixirschool#1524]
First of all, I'm definitely not a lawyer and I'm not really a legal / licensing expert; I just wanted to raise some questions around the license and copyrights, so I can better understand how all written work is being published and distributed.

Currently, when you go to https://elixirschool.com/en the website says:

> © 2018 Sean Callan All rights reserved.

Does this mean that all content (including content contributed by others in the repository) also falls under this clause? Or is that simply for the "ElixirSchool" name and logo/brand?

In the actual repository, there is  actually a `LICENSE` file, that's Apache License 2.0. I haven't got around reading and understanding it yet (legal language...), but the license seems incomplete, since it's missing some information:

>  Copyright {yyyy} {name of copyright owner}

It will be good to clarify how contributed work is being licensed and distributed; and also maybe include a human readable version for contributors, so they know what happens with their work.

I personally find the Creative Commons licenses for written work to be very friendly and easier to understand. On Medium and elsewhere, my preference is usually the [Attribution-NonCommercial-ShareAlike 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license, since it's important for me that anyone can copy, modify or build upon it, but again — I'm just giving it as an example of a clear, easy to understand license, which I think is important.

**Comment by doomspork** [comment]
@svileng we operate similarly to Elixir Lang who's code is licensed under Apache 2.0 but everything else (branding, logos, et al) remains under my ownership for stewardship.

I will update the license filler (something GitHub should have done).  At this time I do not see a reason to change license.

> since it's important for me that anyone can copy, modify or build upon it, but again — I'm just giving it as an example of a clear, easy to understand license, which I think is important.

We don't want people to "borrow" other content people have written and claimed it for their own.  This has already happened before.  No one associated with Elixir School (myself included) is compensated in any way (in fact Elixir School costs me money).  I don't want a license that allows people to take other people's hard work and claim it as their own.

**Comment by doomspork** [comment]
@svileng you can email me directly to discuss this stuff further.  I have some ideas but I need to figure out things before we can proceed with big changes.

**Comment by svileng** [comment]
No problem, I'm happy to take this over email, but just wanted to say that we completely agree on the topic of plagiarism; when I said "anyone can copy, modify or build upon it" I meant it in the context of the CC BY-NC-SA 4.0 license, which states "You must give appropriate credit, provide a link to the license, and indicate if changes were made." etc.

Also I wholeheartedly support the project, so if it sounded like I'm trying to undermine it any way — this was not my intention 😞
