### ISSUE TITLE
Specify directory for Ecto migrations

### ISSUE THREAD

**Issue by ChuckIrvine** [elixirschool/elixirschool#1547]
The lesson on Ecto migrations doesn't say where migration files should be placed. I never could figure this out and kept getting this error from "mix ecto.migrate":

````
warning: could not find Ecto repos in any of the apps: [:example_app].

You can avoid this warning by passing the -r flag or by setting the
repositories managed by those applications in your config/config.exs:

    config :example_app, ecto_repos: [...]

````

**Comment by doomspork** [comment]
@ChuckIrvine if you have a suggestion for how to clear this up, now would be a great opportunity to open a PR with Hacktoberfest on-going.
