### ISSUE TITLE
Extra forward slash in next and previous article buttons

### ISSUE THREAD

**Issue by CarlGraff** [elixirschool/elixirschool#1564]
At least on chrome and safari I get an extra / embedded in the href at the bottom of recent posts pages.

Perhaps the page.next.title and page.previous.title (jekyll variables?) already include a trailing slash and if so then this:
href="{{ page.next.url | prepend: site.baseurl | prepend: site.url }}"
should be:
href="{{ page.next.url | prepend: site.url }}"

in section-prevnext.html

**Comment by doomspork** [comment]
@CarlGraff I'd welcome a PR to fix this if you have the time.  If not, we can find someone else 😁

**Comment by CarlGraff** [comment]
Sure - I’ll take care if it if you want to assign to me.
Also I would like to help fixing/testing Elixir / Phoenix code and perhaps contributing to an article at some point. 
What markdown editor do you use?

Best,
  Carl

**Comment by burden** [comment]
Good find, @CarlGraff 

Looks like we had an incorrect `baseurl` specified in `_config.yml` which was responsible for that extra slash. Thanks for the heads up :)

**Comment by CarlGraff** [comment]
Great I see you already fixed.

Was curious about Jekyll as I had thought is was more like a CI tool such as Jenkins but when exploring found out it  is a lot more interesting and obviously has Ruby roots.

Might poke around and see if there is anything I can help out with if that is OK.

Best,
  Carl

**Comment by burden** [comment]
@CarlGraff indeed I did :) Jekyll is an amazing tool for managing static websites. Feel free to reach out to me if you have any questions or need help with anything.

**Comment by CarlGraff** [comment]
Great to hear and thanks for offering assistance if needed!
