### ISSUE TITLE
Update sidebar

### ISSUE THREAD

**Issue by burden** [elixirschool/elixirschool#1579]
While working on dark theme, it was desirable to place the toggle button at the top of the menu. As it stands, we already have a list of languages, a header, a slogan, and of course the OTP version. This means that the actual site navigation doesn't begin until about half way down the fold. 

Tasks
- [x] Move dark toggle under hamburger icon
- [x]  Place menu features like OTP version, and languages near each other towards the top
- [x] Tighten up spacing where excessive

**Comment by doomspork** [comment]
@burden should we try to recruit someone to help with these changes?

**Comment by burden** [comment]
Figured someone would have jumped on it. If you're just looking to clean out issues now that Hacktober is winding down, I'd be happy to finally make this happen.

**Comment by doomspork** [comment]
ping @burden — do we still need this issue?

**Comment by burden** [comment]
It's on my own todo board-- you can close it if you want.

**Comment by doomspork** [comment]
We can leave if it if it's still on the radar.  Wasn't sure if they were still changes we wanted 👍

**Comment by tajchumber** [comment]
@burden @doomspork I can pick this up if you want!

**Comment by doomspork** [comment]
@tajchumber please do! It's been a few months now so I think this has been shelved by @burden. If this is something you're interested in I'd love to have your input and help 😁

**Comment by Sja91** [comment]
Just a small suggestion on top of this, perhaps change the empty circle to a moon icon.
I went on such a hunt to try to figure this out, and only just now did. The circle just never made me stop and think "Is this it?"
