### ISSUE TITLE
Plug lesson is out of date

### ISSUE THREAD

**Issue by SophieDeBenedetto** [elixirschool/elixirschool#1597]
The plug lesson uses outdate plug and cowboy versions:

```elixir
[
    {:cowboy, "~> 1.1.2"},
    {:plug, "~> 1.3.4"}
  ]
```

Cowboy is now at 2.50 and Plug is at 1.7.1. Two changes I'd like to see:

* Instead of requiring cowboy + plug separately, it is now recommended to require [`plug_cowboy`](https://github.com/elixir-plug/plug_cowboy)
* Instead of calling on `Plug.Adapters.Cowboy`, it is recommended to use `plug_cowboy`'s `Plug.Cowboy`

From the [Plug 1.7 docs](https://hexdocs.pm/plug/Plug.Adapters.Cowboy.html):

> **Plug.Adapters.Cowboy**
> This module is deprecated. To use Cowboy 1 With Plug please include `plug_cowboy` version 1.0 or above in your `mix.exs` file. It is recommended that you use the `Plug.Cowboy` module directly instead of `Plug.Adapters.Cowboy`.

So this:
```elixir 
children = [
      Plug.Adapters.Cowboy.child_spec(:http, Example.Router, [], port: port)
    ]
```

Becomes this:
```elixir
children = [
  {Plug.Cowboy, scheme: :http, plug: Example.Router, options: [port: port]}
]
```

**Comment by doomspork** [comment]
Howdy @SophieDeBenedetto!  Good catch.  I'd be happy to make this change and take a peek at whether the lesson needs any additional updates or you can take a stab at it — your call!

**Comment by doomspork** [comment]
You're awesome — thank you @SophieDeBenedetto!
