### ISSUE TITLE
New Content: Phoenix

### ISSUE THREAD

**Issue by SophieDeBenedetto** [elixirschool/elixirschool#1602]
Elaboration on #1491

* [ ] Getting started: build a super simple app that we can use throughout all of these sections. Something that will accommodate channels and presence nicely. To Do app?
  * [x] Install and generate new project 
  * [ ] Basic routing
  * [ ] Controllers 
  * [ ] Templates and views
  * [ ] Testing Phoenix with ExUnit: initial testing set up and then test basic functionality so far. Write a controller test, for example. 
* [ ] Contexts
  * [ ] Phoenix + Ecto: Elaborate on the To Do app by designing the appropriate contexts, generating migrations and defining schema for lists, items, and users or authors. 
* [ ] Plug (reference existing Plug lesson and take a specific look at using plug in Phoenix for something like validating request params)
* [ ] Building a SPA
  * [ ] Building a simple API
  * [ ] Assets (maybe use Webpack + React to create a simple front-end for the API from the previous section)
* [ ] WebSockets with Phoenix Channels
* [ ] Presence 
* [ ] Advanced
  * [ ] Authentication with Guardian 
  * [ ] JWT Authentication

**Comment by SophieDeBenedetto** [comment]
The above outline is just spit balling. My goal is to have some small, discrete chunks of work that contributors can start biting off and that I can start pitching to some Flatiron folks who might be interested and well equipped to work on this.

**Comment by doomspork** [comment]
Awesome!  This would be a wonderful addition (especially given the translations)

**Comment by gemantzu** [comment]
Would it make sense to add one lesson about testing the Phoenix specific parts? @SophieDeBenedetto great job so far!

**Comment by SophieDeBenedetto** [comment]
Yea @gemantzu a testing lesson would be great! Maybe something in “getting started” on testing Phoenix w ex unit, then write some tests for the functionality that would exist by the end of “getting started” section. Then anyone can add more testing content to specific lessons as-needed.

**Comment by v0idpwn** [comment]
Is this still a thing? I'd like to help on this for hacktoberfest.

**Comment by doomspork** [comment]
@v0idpwn yes! Neither myself nor @SophieDeBenedetto have had the bandwidth to get this started but if you would be interested that would be wonderful!

**Comment by jorgedjr21** [comment]
Hey guys, I have created the first topic (install and generate), can someone take a look, please?

https://github.com/elixirschool/elixirschool/pull/2701

**Comment by doomspork** [comment]
@SophieDeBenedetto now that folks are starting to work on these lessons could you please take the lead on reviewing them?

**Comment by JohnPCarvalho** [comment]
Hey guys! I would like to help translating the content to PT-BR, gonna take some of these new lessons to do the translation.
