### ISSUE TITLE
Function lesson: add pattern matching for function arity

### ISSUE THREAD

**Issue by SophieDeBenedetto** [elixirschool/elixirschool#1606]
We have a super short section on this right now https://elixirschool.com/en/lessons/basics/functions/#pattern-matching

and we expand on it here https://elixirschool.com/en/lessons/basics/functions/#function-naming-and-arity

BUT let's add some discussion of pattern matching function arity + variable assignment. 

For example, how does the following work?

```elixir
defmodule Greeter
  def greet(%{name: name, likes_icecream: true} = person) do 
    greet(person)
    give_icecream(person)
  end
  
   def greet(%{name: name, likes_icecream: false} = person) do 
     greet(person)
  end
end
``` 

We know that the match operator doesn't care about left/right side _but_ this _doesn't_ work:

```elixir
iex> 1 = x
** (CompileError) iex:1: undefined function x/0
```
I think this is a great way to take a closer look at the match operator, developer assumptions of "variable assignment" in elixir and the behavior of function arity.

**Comment by SophieDeBenedetto** [comment]
I should mention that this came up with something we were working on at Flatiron today and we have a team member that would love to write this up :)

**Comment by doomspork** [comment]
Thank you for all your help @SophieDeBenedetto!  This is really exciting to see.  Please let me know if there's anything I can do to help you all 😁

**Comment by meryldakin** [comment]
I'd love to work on this. Thanks @SophieDeBenedetto 🙏

**Comment by SophieDeBenedetto** [comment]
Awesome @meryldakin! Contribution guide is [here](https://github.com/elixirschool/elixirschool/blob/master/CONTRIBUTING.md) and feel free to reach out with any questions 🐶

**Comment by doomspork** [comment]
Welcome @meryldakin!  Let us know if there's anything we can do to help.

@SophieDeBenedetto thanks so much for all of your help recently, it's very much appreciated!
