### ISSUE TITLE
Site is down? "Jekyll is currently rendering the site. Please try again shortly."

### ISSUE THREAD

**Issue by malloryerik** [elixirschool/elixirschool#1626]
Site is down for at least an hour now.
Maybe it really is time to replace Jekyll with Phoenix?... [#523](https://github.com/elixirschool/elixirschool/issues/523)

**Comment by burden** [comment]
Thanks for the heads up @malloryerik

**Comment by doomspork** [comment]
Sorry about that @malloryerik, that's my fault 😰

I've fixed the site so it renders but we'll going to need to fix some the dependencies I changed in #1623

**Comment by malloryerik** [comment]
> Sorry about that @malloryerik, that's my fault 😰
> 
> I've fixed the site so it renders but we'll going to need to fix some the dependencies I changed in #1623

Thanks so much for Elixir School! It's one of the only really good resources with translations in several languages.

**Comment by doomspork** [comment]
@malloryerik thank you so much for the kind words ❤️
