### ISSUE TITLE
[New Lesson] Specifices: Code Quality

### ISSUE THREAD

**Issue by SophieDeBenedetto** [elixirschool/elixirschool#1636]
- [ ]  Dialyzer/Dialyxer + type specs

  * Currently there is a brief section on Dialyxir in the [Debugging](https://elixirschool.com/en/lessons/specifics/debugging/) section. I think it would make more sense to pull that section out of Debugging and include a more in-depth look in a "Code Quality" section. Could be something like
  - [ ] Installing/Getting Started
  - [ ] Dialyxir and TypeSpecs 
  - [ ] Common Error Messages/Understanding Dialyxir output
- [ ] Credo 
   - [ ] Intallation/Getting started
   - [ ] Usage
     - [ ] Analyzing a project/understanding output
     - [ ] Analyzing a specific file 
     - [ ] Configuration
  - [ ] Advanced: Using Credo in your CI Set up: could be brief, pointing to some other resources since there are so many different CI set ups.

**Comment by doomspork** [comment]
I _love_ this idea!  I'm a huge advocate for code quality and I think teaching that alongside the fundamentals is brilliant idea 👍

**Comment by SophieDeBenedetto** [comment]
sweet! We recently set up Credo to run with our CI across all of our Elixir apps at Flatiron so I'm gonna see if I can't find someone interested in claiming those lessons.

**Comment by doomspork** [comment]
Awesome!  I love Credo and use it on all my of projects, I'd be happy to help whomever with those lessons. 

It might be best to use TravisCI for these lessons since _most_ open source projects use it so folks will have exposure to Travis.  We use both on [admissions](https://github.com/elixirschool/admissions/blob/master/.travis.yml)

**Comment by sotojuan** [comment]
`mix format` should probably be mentioned, though its relation to credo might need elaboration. While they aren't the same, they share some of the same use cases.

**Comment by doomspork** [comment]
Additionally, @sotojuan a blog post that goes into Credo vs Formatter could be really informative.  What do you think?

**Comment by sotojuan** [comment]
Yeah sounds good, shouldn't be too hard as credo's readme shows a lot of what it does vs. just format.
