### ISSUE TITLE
TIL: Different ways to Add in Elixir

### ISSUE THREAD

**Issue by juddey** [elixirschool/elixirschool#1640]
Hey! 

Saw @SophieDeBenedetto talking on twitter about elixir school, did a quick browse of the issues, saw the TIL for iex labels and wondered whether you'd be interested in something similar for adding up numbers, based on the Advent of Code Day 1 exercise?

**Comment by doomspork** [comment]
@juddey absolutely!  We'd love to have more blog posts from the community

**Comment by doomspork** [comment]
Howdy @juddey, just thought I'd follow up and see if you still had interest in writing this post?

**Comment by juddey** [comment]
Hey @doomspork, Yep sure do.... Been doing more things in elixir and I've even had other ideas too.

**Comment by doomspork** [comment]
@juddey that's _very_ exciting! We'd welcome any blog post you've got ideas for (or any other contributions) 😁 

Hope you're having a great weekend 🎉

**Comment by doomspork** [comment]
@juddey I'm going to close this issue but we'd love to have your contributions 😁
