### ISSUE TITLE
Add section on IEx.pry in Specifics>Debugging 

### ISSUE THREAD

**Issue by cryic** [elixirschool/elixirschool#1643]
The article on Debugging in 'Specifics>Debugging' [here](https://elixirschool.com/en/lessons/specifics/debugging/) could use an entry for IEx.pry.

Thinking a basic start about using within `iex` and `mix` contexts.

I'll work on an initial take, if people think this would be useful.

Thanks!

**Comment by doomspork** [comment]
@cryic thank you for the suggestion, I think we should absolutely add some coverage of `IEx.pry`.  

If you'd be open to kicking this off myself and others would be happy to help you once we get into review.

**Comment by doomspork** [comment]
Thank _you_ @cryic 😁

**Comment by brain-geek** [comment]
@cryic Hey, how is it progressing? Would it be ok for you if I implement this?

**Comment by cryic** [comment]
Hi! Yes, please implement this!

I’d made a rough draft but then sadly never finished.

Thanks for asking, good luck!
