### ISSUE TITLE
TIL: using `@moduletag capture_log: true`

### ISSUE THREAD

**Issue by alexgriff** [elixirschool/elixirschool#1645]
When writing ExUnit tests for "sad path" code flows you may expect error messages to be logged as part of the desired/expected error handling process. Running your test suite then results in a lot of noise and the appearance that there are failures in the tests. I thought a good idea for a TIL would be to cover how adding `@moduletag capture_log: true` will suppress the error output so you can see a nice list of green passing tests without the noise.

**Comment by doomspork** [comment]
@alexgriff this would be a wonderful TIL!  Would you be open to contributing a blog post on the topic?

**Comment by alexgriff** [comment]
@doomspork Yeah that would be great!

**Comment by doomspork** [comment]
Fantastic!  We'd love to have your contributions @alexgriff 😁

**Comment by doomspork** [comment]
@alexgriff would you be open to submitting a PR for this week's TIL?

**Comment by alexgriff** [comment]
@doomspork sure! I will set aside some time today to work on it
