### ISSUE TITLE
Blog post: Connecting kafka to elixir through client

### ISSUE THREAD

**Issue by meryldakin** [elixirschool/elixirschool#1646]
I think this would make a good blog post because neither of them have a lot of resources outside of their docs. This could be a walk-through of how to hook it up to a small existing elixir app that's communicating with a running instance of Kafka. It wouldn't set up Kafka, just the client on the app. 

I'm not sure which client to do this on - I've successfully hooked up `kaffe` before but `kafka_ex` seems to have more support in general. Any thoughts on this?

**Comment by doomspork** [comment]
@meryldakin great idea! 

Whichever client you've worked with I think would be fine to cover.  We can be more flexible with the content (and libraries) inside blog posts since we expect them to cover a wider swath of the ecosystem than the lessons do.

**Comment by SophieDeBenedetto** [comment]
closed by #1675
