### ISSUE TITLE
TIL blog post from Flatiron School: How to Run Ecto Migrations on Production

### ISSUE THREAD

**Issue by SophieDeBenedetto** [elixirschool/elixirschool#1659]
Would love to cross-post the latest Flatiron blog post from @ktravers https://medium.com/flatiron-labs/how-to-run-ecto-migrations-on-production-6fe47f10027f. I think it would make a great TIL and we can preface it with a little blurb about how its a cross-post from flatiron labs blog.

**Comment by doomspork** [comment]
@SophieDeBenedetto I'm onboard 👍 

We can add a note for now RE: cross-post while we look into better support for it.
