### ISSUE TITLE
When to use IEx Output in the examples?

### ISSUE THREAD

**Issue by disappearer** [elixirschool/elixirschool#1681]
I was thinking of adding a contribution, specifically for the mnesia tutorial, but I'm unclear about when is it appropriate to use an iex output block and when to use a regular code block. For example, for this block
```elixir
iex> case Mnesia.create_table(Person, [attributes: [:id, :name, :job, :age]]) do
...>   {:atomic, :ok} ->
...>     Mnesia.add_table_index(Person, :job)
...>     Mnesia.add_table_index(Person, :age)
...>   {:aborted, {:already_exists, Person}} ->
...>     case Mnesia.table_info(Person, :attributes) do
...>       [:id, :name, :job] ->
...>         Mnesia.transform_table(
...>           Person,
...>           fn ({Person, id, name, job}) ->
...>             {Person, id, name, job, 21}
...>           end,
...>           [:id, :name, :job, :age]
...>           )
...>         Mnesia.add_table_index(Person, :age)
...>       [:id, :name, :job, :age] ->
...>         :ok
...>       other ->
...>         {:error, other}
...>     end
...> end
```
to me it makes more sense for it to be a regular code block and not an iex session, since there's no actual output and I find it generally more readable without the extra characters. My question is what is the reasoning behind this and would it be okay if I converted it to a regular block of code?

**Comment by doomspork** [comment]
@disappearer this _should_ be a code block, please do make this change 👍  I've never come up with a "rule" for this but in general we try to express most snippets as Elixir blocks and only the small tidbits with output in the shell/iex blocks.

Does that help?

**Comment by disappearer** [comment]
Yes, it does help. Thanks 🙂
