### ISSUE TITLE
More info in documentation

### ISSUE THREAD

**Issue by kritik** [elixirschool/elixirschool#1696]
Ijust learn elixir and got in stuck in topic [Documentation](https://github.com/elixirschool/elixirschool/blob/master/en/lessons/basics/documentation.md#documenting-modules) I run code in iex like in example but cannot get same result
```
iex(27)> defmodule Greeter do
...(27)>   @moduledoc """
...(27)>   Provides a function `hello/1` to greet a human
...(27)>   """
...(27)> 
...(27)>   def hello(name) do
...(27)>     "Hello, " <> name
...(27)>   end
...(27)> end
warning: redefining module Greeter (current version defined in memory)
  iex:27

{:module, Greeter,
 <<70, 79, 82, 49, 0, 0, 4, 208, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 141,
   0, 0, 0, 15, 14, 69, 108, 105, 120, 105, 114, 46, 71, 114, 101, 101, 116,
   101, 114, 8, 95, 95, 105, 110, 102, 111, 95, ...>>, {:hello, 1}}
iex(28)> c("greeter.ex")
** (ArgumentError) could not find files greeter.ex
    (iex) lib/iex/helpers.ex:180: IEx.Helpers.c/2
iex(28)> h Greeter
Greeter was not compiled with docs
```

It seems that I need to save this module in the file and compile with doc allowed. I think this part needs more explanation for beginners in Elixir.

**Comment by kritik** [comment]
My proposal is to write text with smth like, "Open your favorite text editor and write next code and save it". But I don't know what to do next :)

**Comment by SophieDeBenedetto** [comment]
Thanks for opening this issue @kritik! I went through the code example and ran into the same issue. In order to get this example working you have to:

1. Create a file, `greeter.ex`
2. Paste in the `Greeter` module code described in the lesson
3. From the terminal, compile the file like this:

```
elixirc greeter.ex
```

4. Open an `iex` console from your terminal:

```
iex
```

5. In the iex console, run 

```
iex> h Greeter
```

And _then_ you should see:

```
                                    Greeter                                     

Provides a function hello/1 to greet a human
```

We can definitely update the lesson to include these clear instructions. Thanks!

**Comment by gemantzu** [comment]
Maybe we should add a section in [Basics](https://elixirschool.com/en/lessons/basics/basics/) on how to do proper handling of files in elixir (all this functionality that @SophieDeBenedetto describes above, plus .exs files)?

I can't seem to find us having this info anywhere, but if we do, should we move it to a proper section?

**Comment by doomspork** [comment]
I think the simplest solution with the least impact is adding some mention to this lesson about the file. I just went through it again myself and we don't mention creating that file. In other lessons we do a better job of instructing the user on what to do, we fall short on this one.

**Comment by gemantzu** [comment]
I think that adding this guide in basics, will also help in other lessons as well. We can always link back to that section as needed in some lessons as a reminder

**Comment by doomspork** [comment]
What guide exactly @gemantzu?

**Comment by gemantzu** [comment]
Guide on how to write a file and compile it / run it.

**Comment by doomspork** [comment]
@gemantzu @kritik would either of you like to tackle this improvement as part of Hacktoberfest?

**Comment by iampeterbanjo** [comment]
I can pick this up if its still up for grabs

**Comment by brain-geek** [comment]
@iampeterbanjo Hey, are you still going to take it, or it's available?

**Comment by iampeterbanjo** [comment]
@brain-geek please go ahead, thanks :)
