### ISSUE TITLE
Sass gem deprecation warning

### ISSUE THREAD

**Issue by gemantzu** [elixirschool/elixirschool#1723]
```cmd
Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  http://sass.logdown.com/posts/7081811
```
Running bundle install, we are warned with this. How should we proceed? just add sassc and be done with it? Are there any known issues with this swap?

**Comment by doomspork** [comment]
@elixirschool/developers any thoughts?

**Comment by tajchumber** [comment]
as of Ruby Sass's own [reccomendation](https://github.com/sass/ruby-sass/blob/5bf50c5d53b04c91dc09a7ae006b5071bdf1773d/sass.gemspec#L46-L47), I think we should migrate to [sassc-ruby](https://github.com/sass/sassc-ruby#readme)

**Comment by doomspork** [comment]
Sounds good to me @tajchumber, can you lead the charge?

**Comment by brain-geek** [comment]
Actually, it's fixed in upstream. https://github.com/jekyll/jekyll-sass-converter/issues/74

I'll look into it today, maybe it would be possible to fix this fast.

**Comment by brain-geek** [comment]
Okay, so after some time investigating I believe it's not yet achievable without forking stuff. On the Rubygems version is still legacy for jekyll-sass-converter, on github 

Jekyll [needs sass-converter](https://github.com/jekyll/jekyll/blob/master/jekyll.gemspec#L40), which [requires sassc 2.0](https://github.com/jekyll/jekyll-sass-converter/blob/master/jekyll-sass-converter.gemspec#L21)
But jekyll-assets [requires sassc ~1.11](https://github.com/envygeeks/jekyll-assets/blob/master/jekyll-assets.gemspec#L37). 

And bundler does not have 'force version' [feature yet](https://github.com/bundler/bundler/issues/4552).  

The simplest way would be waiting until everything updates.

**Comment by tajchumber** [comment]
sorry I haven't been very active lately! Terribly busy at work!

**Comment by doomspork** [comment]
No worries @tajchumber, thank you for the update 😁

**Comment by tajchumber** [comment]
@brain-geek if I understand correctly... this is something that Jekyll will fix right?

if that's case I think we can close this issue :)

**Comment by doomspork** [comment]
@burden want to look into updating Jekyll and friends as part of Hacktoberfest?
