### ISSUE TITLE
Proposal: Add Advanced Section content for OTP Debugging

### ISSUE THREAD

**Issue by notactuallypagemcconnell** [elixirschool/elixirschool#1726]
Currently there is no content on GenServer debugging.

However, the `:sys` erlang module provides a great interface for debugging GenServers in a variety of ways. They are documented a bit in the GenServer docs, but we could totally make a nice concise writeup on tracing your system's GenServer's messages.

**Comment by notactuallypagemcconnell** [comment]
I would be happy to write this.

**Comment by doomspork** [comment]
We already have a debug section here: https://elixirschool.com/en/lessons/specifics/debugging/, do we need to make additions here?

@elixirschool/english / @elixirschool/developers thoughts on these?

**Comment by notactuallypagemcconnell** [comment]
@doomspork yeah I think this would fit better in there after seeing. Was specifically thinking OTP and missed that part cuz I was in that section. Specifically I am thinking of covering `:sys.statistics` and `:sys.trace` - definitely small enough it could just fit in there.

**Comment by doomspork** [comment]
Let's do it @notactuallypagemcconnell 👍

**Comment by doomspork** [comment]
@notactuallypagemcconnell I'm still open to this if you want to tackle it. This could also be a good blog post. 

Closing the issue now that we don't need to discuss this further.
