### ISSUE TITLE
TIL Blog Post: Difference between validations and constraints

### ISSUE THREAD

**Issue by maxcell** [elixirschool/elixirschool#1742]
TIL When you want to ensure your application has correct data, it is important to implement either a validation and/or a constraint. They have different roles for Ecto and how to ensure they are getting checked. A constraint will be required to be implemented at the database level otherwise Ecto will pass over it.

**Comment by doomspork** [comment]
This would be terrific @maxcell, would you be open to writing this post?

**Comment by maxcell** [comment]
Yup! Sounds perfect to me. 😁

**Comment by SophieDeBenedetto** [comment]
Awesome, and welcome @maxcell!!
