### ISSUE TITLE
Error when starting iex in ecto lessons

### ISSUE THREAD

**Issue by Exadra37** [elixirschool/elixirschool#1755]
Today when following the lesson about [Ecto Basics](https://elixirschool.com/en/lessons/ecto/basics/#schemas) I run in this error:

```bash
╭─elixir@6da418c1ce55 ~/workspace/friends  ‹basics*› 
╰─$ iex       
Erlang/OTP 21 [erts-10.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Interactive Elixir (1.8.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> %Example.Person{}
** (CompileError) iex:1: Example.Person.__struct__/1 is undefined, cannot expand struct Example.Person
```

This happens because **iex** needs to start with `iex -S mix` instead of just `iex` as a newbie may think after reading: 

> Let’s take a peek at our schema by opening `iex` and creating a new person:

In my opinion would be better to have:

> Let’s take a peek at our schema by opening `iex -S mix` and creating a new person:

This improved sentence will avoid newbies to get stuck :)

```bash
╭─elixir@6da418c1ce55 ~/workspace/friends  ‹basics*› 
╰─$ iex -S mix
Erlang/OTP 21 [erts-10.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Interactive Elixir (1.8.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> %Example.Person{}
%Example.Person{
  __meta__: #Ecto.Schema.Metadata<:built, "people">,
  age: 0,
  id: nil,
  name: nil
}
iex(2)>
```

**Comment by doomspork** [comment]
@Exadra37 thanks for pointing this out, pull requests are more than welcome for things like this 👍
