### ISSUE TITLE
Possible typo in functions arity on lesson about Ecto Changeset Custom Validators 

### ISSUE THREAD

**Issue by Exadra37** [elixirschool/elixirschool#1757]
From lesson [Ecto Changesets Custom Validations](https://elixirschool.com/en/lessons/ecto/changesets/#custom-validations):

```elixir
@fictional_names ["Black Panther", "Wonder Woman", "Spiderman"]
def validate_fictional_name(changeset) do
  name = get_field(changeset, :name)

  if name in @fictional_names do
    changeset
  else
    add_error(changeset, :name, "is not a superhero")
  end
end
```
> Above we introduced two new helper functions: get_field/3 and add_error/4. What they do is almost self-explanatory, but I encourage you to check the links to the documentation.

In my understanding:
* `get_field/2` is being used in the lesson code, not `get_field/3`.
* `add_error/3` is being used in the lesson code, not `add_error/4`.

**Comment by lccezinha** [comment]
@Exadra37 Check the documentation for both functions:

- https://hexdocs.pm/ecto/Ecto.Changeset.html#get_field/3
- https://hexdocs.pm/ecto/Ecto.Changeset.html#add_error/4

The last param for each function has a default value as `nil` and `[]` respectively, that is why these arguments do not need to be used in the functions, the lesson is correct.

**Comment by tajchumber** [comment]
the arity of `get_filed` is both 2 and 3 and the arity of `add_error` is both 3 and 4.

You check this by running `Ecto.Changeset.__info__(:functions)` in `iex`:

```elixir
[
  ...
  add_error: 3,
  add_error: 4,
  ...
  get_field: 2,
  get_field: 3,
  ...
]
```

(closing this issue)
