### ISSUE TITLE
LiveView blog post fixes

### ISSUE THREAD

**Issue by gemantzu** [elixirschool/elixirschool#1777]
1. fix the numbering on the installation steps
2. change the file name to 2019, it is 2018
3. `MyAppWeb.GithubDeployView.handle_info/2` matching on {:push_contents, repo} has probably a wrong variable assignment, as below we use the var `org` which is not assigned anywhere.
4. You have to make it more specific that the old template (`page/index.html.eex`) must be removed before this will be able to work, as the way it is now, with both files in the folder, it throws an error.

**Comment by SophieDeBenedetto** [comment]
Thanks for pointing these out @gemantzu! I'll have a PR ready soon :)

**Comment by gemantzu** [comment]
Thank you for the nice tutorial btw :)
