### ISSUE TITLE
TIL blog post: How to use Ecto.Query#select_merge/3

### ISSUE THREAD

**Issue by ktravers** [elixirschool/elixirschool#1953]
Hello! I'd love to cross-post a recent post I wrote for the flatiron labs blog about my new fave Ecto query function, `Ecto.Query#select_merge/3`: https://medium.com/flatiron-labs/til-how-to-select-merge-with-ecto-query-679d03204b9d

It includes examples of how and when to use it, as well as pros/cons versus another (totally valid) approach like adding more schema associations.

**Comment by tajchumber** [comment]
hello @ktravers we're happy to accept a PR for this
Please follow the [lesson styleguide](https://github.com/elixirschool/elixirschool/wiki/Lesson-Styleguide)

also you can follow the what @SophieDeBenedetto did [here](https://github.com/elixirschool/elixirschool/blob/master/_posts/2019-06-04-live-view-with-channels.md).

Let us know if you need any help!
