### ISSUE TITLE
French Translations

### ISSUE THREAD

**Issue by pjhampton** [elixirschool/elixirschool#196]
## Get Involved!

We are seeking **French** translators for this project. If you would like to get involved with translating a lesson. Please folk the project and start translating.
- **Set up**
  - [x] _config.yml
  - [x] index.md 
- **Basics**
  - [x] Basics (@tchoutri)
  - [ ] Collections (@julienXX)
  - [x] Enum (@julienXX)
  - [x] Pattern Matching (@julienXX)
  - [x] Control Structures (@julienXX)
  - [x] Pipe Operator (@julienXX)
  - [ ] Functions (@tchoutri)
  - [ ] Composition (@julienXX)
  - [ ] Mix
  - [ ] Sigils
  - [ ] Documentation (@tchoutri)
  - [ ] Testing
  - [ ] Custom Mix Tasks
- **Advanced**
  - [ ] concurrency.md
  - [ ] errors.md
  - [ ] erlang.md
  - [ ] escripts.md
  - [ ] otp-concurrency.md
  - [ ] otp-supervisors.md
  - [ ] metaprogramming.md
- **Specifics**
  - [ ]  ecto.md
  - [ ]  eex.md
  - [ ]  ets.md
  - [ ]  mnesia.md
  - [ ]  plug.md

**Note**
Those new to Elixir and / or Github are encouraged to get involved :smile:. 1 [Pull Request](https://help.github.com/articles/using-pull-requests/) per lesson.

**Comment by tchoutri** [comment]
I started the french translation and would gladly accept any corrections to the mistakes I could have made!

**Comment by pjhampton** [comment]
Hey @julienXX and @tchoutri!

Can one of you guys please update the **_config.yml** file? 

Also, when working on a new lesson, can you please update the comment at the stop of this issue so there is no work conflicts?

:smile:

**Comment by julienXX** [comment]
@pjhampton sure but there's no way to update the comment.

**Comment by pjhampton** [comment]
Hey @julienXX 

Hmm, in that case Julien, please just post here to say what you are currently working on until @doomspork grants one or both of you collaborator roles.  Hopefully we can get those two lessons + index merged today.

**Comment by julienXX** [comment]
Okay I'm working on Enum right now.

**Comment by pjhampton** [comment]
Hey @julienXX & @tchoutri 

Are you guys on Slack? https://elixir-slackin.herokuapp.com/

We have our channel #elixirschool if you would like to get involved?

**Comment by julienXX** [comment]
Working on Pattern matching chapter.

**Comment by tchoutri** [comment]
@pjhampton just joined ;-)

**Comment by julienXX** [comment]
Working on Pipe operator.

**Comment by tchoutri** [comment]
Working on basics/Functions

**Comment by tchoutri** [comment]
@julienXX J'ai trouvé sur Linguee une traduction pour "n-class citizen" => http://www.linguee.fr/francais-anglais/traduction/consid%C3%A9r%C3%A9+comme+des+citoyens+de+second+ordre.html.
Je propose qu'on s'y tienne au lieu de traduire littérale par "Citoyen de n-classe". Qu'en penses-tu ?

**Comment by julienXX** [comment]
@tchoutri carrément, la traduction littérale sonne pas bien.

**Comment by tchoutri** [comment]
J'ai jugé bon d'inclure la traduction française de pattern matching dans une des sections : 

>Le Pattern matching (ou « Filtrage par motif » en Français)

à titre indicatif. Je vais quand même rester sur l'anglais pour ce terme, ça parle à plus de monde et de façon plus générale, il y a plus de ressources sous ce nom.

**Comment by tchoutri** [comment]
@julienXX Je veux bien ton avis sur les `guards`. On traduit comment ? (ou on laisse tel quel ?)

**Comment by julienXX** [comment]
Je ferais comme pour pattern matching, on le traduis une fois entre parenthèses (gardes dans les livres Erlang en français) puis on garde le terme anglais.

**Comment by tchoutri** [comment]
oké :)

**Comment by julienXX** [comment]
Working on Collection.

**Comment by julienXX** [comment]
Working on Composition.

**Comment by tchoutri** [comment]
Working on Documentation

**Comment by tchoutri** [comment]
@julienXX Je suis en train de traduire "Elixir core" par "Bibliothèque standard". Tu as quelque chose de différent en tête ?

**Comment by tchoutri** [comment]
okay merci :)

**Comment by mikaoelitiana** [comment]
Salut les gars, je me lance dans elixir et je voudrais également participer à la traduction de la doc en FR. Je ne sais pas si la checklist est à jour mais je vais commencer par basics/testing.

**Comment by julienXX** [comment]
@mikaoelitiana hello, je pense que la liste est à jour. N'hésite pas à me ping pour une review :)

**Comment by mikaoelitiana** [comment]
@julienXX c'est entendu, merci

**Comment by mikaoelitiana** [comment]
@julienXX un nouveau PR à valider ici #493
