### ISSUE TITLE
Italian Translations

### ISSUE THREAD

**Issue by pjhampton** [elixirschool/elixirschool#197]
## Get Involved!

We are seeking **Italian** translators for this project. If you would like to get involved with translating a lesson. Please folk the project and start translating.
- **Set up**
  - [x] _config.yml (@apeacox)
  - [x] index.md (@apeacox)
- **Basics**
  - [x] Basics
  - [x] Collections
  - [x] Enum
  - [x] Pattern Matching
  - [x] Control Structures
  - [x] Pipe Operator
  - [x] Functions
  - [x] Composition
  - [x] Mix
  - [x] Sigils
  - [ ] Documentation
  - [ ] Testing
  - [ ] Custom Mix Tasks
- **Advanced**
  - [ ] concurrency.md
  - [ ] errors.md
  - [ ] erlang.md
  - [ ] escripts.md
  - [ ] otp-concurrency.md
  - [ ] otp-supervisors.md
  - [ ] metaprogramming.md
- **Specifics**
  - [ ]  ecto.md
  - [ ]  eex.md
  - [ ]  ets.md
  - [ ]  mnesia.md
  - [ ]  plug.md

**Note**
Those new to Elixir and / or Github are encouraged to get involved :smile:. 1 [Pull Request](https://help.github.com/articles/using-pull-requests/) per lesson.

**Comment by apeacox** [comment]
I'm going to translate it ✌🏼

**Comment by pjhampton** [comment]
Hey @apeacox 

That's awesome! Thank you so much :smile: Obviously this is a big job so we encourage you to get your friends involved as well. This can help speed up reviewing, etc. 

We have our own slack channel (#elixirschool) if you are not there already - https://elixir-slackin.herokuapp.com/ - You will find most of us there.

Chat soon! :+1:

**Comment by apeacox** [comment]
Ok, I'm joining the chat right now :+1: 

I will ping some friend to review my translations, once they grow. `_config.yml` and `index.md` are done. Starting with `basics.md` :D

**Comment by pjhampton** [comment]
Awesome @apeacox! #241 looks good to me. :+1:

**Comment by apeacox** [comment]
I've translated a bunch of new chapters for the `basics` section :-)

**Comment by doomspork** [comment]
@apeacox I updated the checklist above but now that you're a contributor on the repo you can keep it updated :+1:

**Comment by omissis** [comment]
@apeacox maybe I could help with Reviews? I'd love to translate some chapters myself but I just don't have enough time for that now

**Comment by apeacox** [comment]
@omissis every help is more than welcome ✌🏻️
I have to create a PR with the latest fixes to the current merged lessons, plus two new translated lessons. So you can at least review/fix what's already done 😉

In case you want to translate some lesson, please let me know which ones, so that we can make some plan to avoid overlapping.

**Comment by apeacox** [comment]
@omissis I have created a new pull request (#264) with a new lesson and a bunch of fixes. Feel free to review it ;-)

I'm going to merge the PR in the next few days (waiting for some feedback/fix)

**Comment by omissis** [comment]
@apeacox I have started reviewing it, more or less 50% done. Will continue in the next days as it's 3AM already 😱 Let me know what you think so far. Imho we could also review the verbs tenses and make 'em consistent across the whole guide, once we decide which one we're gonna use.

**Comment by sobolevn** [comment]
May I also take `eex` (the same task as I took in [russian](https://github.com/doomspork/elixir-school/issues/220#issuecomment-223753441))?

Or should we do it step by step?

**Comment by doomspork** [comment]
@sobolevn I don't see a problem with this 👍

**Comment by sobolevn** [comment]
@doomspork Thanks, I am translating `eex` then.
