### ISSUE TITLE
RSS  Feed?

### ISSUE THREAD

**Issue by andyl** [elixirschool/elixirschool#1999]
Is there an RSS Feed for the Blog?

**Comment by doomspork** [comment]
What timing @andyl! I was just discussing our lack of RSS feed with another contributor. Would you be up for investigating how to add an RSS feed to the blog?

**Comment by andyl** [comment]
> Would you be up for investigating how to add an RSS feed to the blog?

Have a look at this...

https://joelglovier.com/writing/rss-for-jekyll

**Comment by doomspork** [comment]
One of our contributors, @burden, is a Jekyll pro and may be able to lend a hand if you're interested

**Comment by andyl** [comment]
@doomspork that's great.  I can do research, participate in discussion and test, but don't have time to submit PRs.

**Comment by tajchumber** [comment]
can we close this? :)

**Comment by andyl** [comment]
Works.  Thanks @delta1
