### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by lex111** [elixirschool/elixirschool#2048]
The site is lacking in search. It is easy to add using Algolia.

@doomspork what are some thoughts about UI search?

**Comment by doomspork** [comment]
@lex111 that would be great! Algolia provides a free tier for community projects so I'm 💯 behind this.

In general I'm for any and all improvements we can do to the site to make the content more accessible. I will be the first to admit that UX isn't my strong suit 😁

**Comment by doomspork** [comment]
Thoughts @elixirschool/developers?

**Comment by tajchumber** [comment]
I had a look at it and it seems pretty trivial to add algolia (https://github.com/algolia/jekyll-algolia)
if someone wants to tackle this issue, it would be great! otherwhise I can try to fit it in

**Comment by brain-geek** [comment]
We could also add google search. https://cse.google.com/cse/ could limit the search scope to one site and is free.

**Comment by tajchumber** [comment]
algolia is also free for OSS

**Comment by lex111** [comment]
Here the problem and the main difficulty is the UI (design). Algolia is the best choice for OSS projects.

**Comment by tajchumber** [comment]
I'm working on a solution for this rn, I will be able to share the branch real soon!

**Comment by TrevorAbram** [comment]
> I'm working on a solution for this rn, I will be able to share the branch real soon!

Hey are you still working on this? What route did you decide?

**Comment by thiamsantos** [comment]
@tajchumber Are you still working on this? If not I would be glad to give it a try.

> Here the problem and the main difficulty is the UI (design).

About the UI, I was thinking in adapt to the colors and UI of elixirschool, but add a search box similar to the one used in hexdocs. WDYT @elixirschool/developers ?

![image](https://user-images.githubusercontent.com/13632762/94739847-f9984780-0347-11eb-84cf-0ef6b21ab95d.png)

**Comment by tajchumber** [comment]
@thiamsantos sorry I didn't have the time to work on this
if you want to give this a try please do! :)

**Comment by thiamsantos** [comment]
I got a draft of the search working, but I'm not been able to find quality time to finish it. If anyone is available feel free to give it a try.

**Comment by doomspork** [comment]
I am going to close this for now and create a new issue in the new project's repo. I will reach out to Algolio about an open source account which should remove some of our limitations.
