### ISSUE TITLE
Need update DateTime lesson

### ISSUE THREAD

**Issue by marocchino** [elixirschool/elixirschool#2062]
https://github.com/elixir-lang/elixir/commit/b8b1a4ba8af8256567f00e6d9f7fa056881a8ec1

Since elixir 1.8.0, DateTime start to support time zone.

**Comment by doomspork** [comment]
@marocchino do you want to take the first stab at this or are you open to someone else jumping on this?

**Comment by marocchino** [comment]
Maybe I do it unless someone else does it? Currently I am just waiting for others.
