### ISSUE TITLE
Spell Checker CI

### ISSUE THREAD

**Issue by vbrazo** [elixirschool/elixirschool#2124]
Would we consider adding a `Spell Checker CI` for this repository?

I think that'd be a huge plus and would help us detect the typos faster.

If you've never heard about it, please check this link https://typoci.com/ out and let me know your thoughts.

**Comment by doomspork** [comment]
I'm open to trying it out @vbrazo. I can look at setting it up later today

**Comment by vbrazo** [comment]
We've implemented this CI in the [V by example repository](https://github.com/v-community/v_by_example). Check [this PR](https://github.com/v-community/v_by_example/pull/65/files) out to see how it works.

**Comment by vbrazo** [comment]
I think we need to ignore `elixir` keywords. I noticed that the Speller CI is trying to auto-correct them. 

@MikeRogers0 any plans to ignore the keywords by default in Spell Checker CI?

**Comment by MikeRogers0** [comment]
@vbrazo I can add them today :) Do you have a source where I can get a list of the elixir keywords?

**Comment by doomspork** [comment]
I put these in the config: https://github.com/elixirschool/elixirschool/blob/master/.typo-ci.yml#L40-L44

Shouldn't they be ignored?

**Comment by vbrazo** [comment]
@MikeRogers0 I don't have the list yet, but this looks like an interesting challenge because programming languages often break some changes, so you'll need to watch the keywords breaking changes.

**Comment by vbrazo** [comment]
@MikeRogers0 I see that there are still some Spell Checker suggestions that need to be improved. I totally understand that you're still building the CI and it will improve some time to get mature. I was wondering if it could be possible to allow users to classify the suggestion. Let's jump on an example:

<img width="740" alt="Screen Shot 2019-11-30 at 1 42 33 PM" src="https://user-images.githubusercontent.com/1292556/69906387-5ff2b900-1377-11ea-9bff-953bb8fe8a65.png">

Let's say that this suggestion is wrong and I'd like to classify it as a bad answer, so in the future you won't suggest me this again, because it's wrong. Would that be possible?

**Comment by MikeRogers0** [comment]
@vbrazo Yes 100%! I'm working on a github action to suggest words, so it should be as easy as clicking a button :)

**Comment by vbrazo** [comment]
That's awesome! This will help us help you ;)

**Comment by vbrazo** [comment]
Once it's done, please post here the feature/button. Other maintainers should know this.

**Comment by MikeRogers0** [comment]
@vbrazo Awesome, I will! I'm aiming for next weekend so 🤞

Thank you again! You're really helping me improve this so much :)

**Comment by vbrazo** [comment]
@MikeRogers0 We have several spell issues in this repository when people open PRs and I believe in any other documentation repositories. So your solution is welcome to solve this problem.

Another thing that I was thinking is the ability to add a new spell issue. Let's say that your CI didn't recognize one issue but one of our maintainers did, how can we send this piece of correction to you?

**Comment by MikeRogers0** [comment]
@vbrazo I'm hoping a similar mechanism for reporting issues where it's a button click, then maybe a small form that'll add new words to the database & refresh the analysis.

**Comment by doomspork** [comment]
Thank you so much for collaborating with us @MikeRogers0! I hope you find these exchanges useful. It's wonderful being a part of the product's development as an early adopter :grin:

**Comment by MikeRogers0** [comment]
![image](https://user-images.githubusercontent.com/325384/70392218-7af7a580-19d5-11ea-974f-15dded156276.png)

@vbrazo I've been experimenting a little this weekend, what do you think of a button like this that'll update the PR/branch with a commit updating the `.typo-ci.yml` file?
