### ISSUE TITLE
GenStage: Add section on ConsumerSupervisor

### ISSUE THREAD

**Issue by tr00gle** [elixirschool/elixirschool#2196]
How do we feel about adding a subsection to the GenStage lesson on the `ConsumerSupervisor` behavior?

I think it would be a nice addition to the lesson. It's a powerful part of GenStage, and we can use it to further solidify some of the already established concepts from the `otp-supervisors` lesson.  I'd be happy to take this on. I use the behavior in my elixir service at work, and I just gave a [talk](https://www.youtube.com/watch?v=x-JlgR0dySg&t=1s) on it as well. 

I think I can have this turned around in the next 2-3 weeks.

**Comment by SophieDeBenedetto** [comment]
Thanks for opening this issue @tr00gle! I think this section would be a great addition to the GenStage lesson. Feel free to open a PR and we'll take it from there!
