### ISSUE TITLE
[FR] Typos in index.md

### ISSUE THREAD

**Issue by jcrevits** [elixirschool/elixirschool#2257]
Hi there, just stumbled upon https://elixirschool.com while diving into Elixir and spotted a few typos in `index.md` - maybe I could fix them?

Some examples:
`déstination` -> `destination`
`Gràce au` -> `Grâce au`

First time opening an issue anywhere so I hope this is OK! I'll then make a PR 🙏 Merci ! 🇫🇷

**Comment by doomspork** [comment]
Thanks again for getting involved @jcrevits! We hope you’ll continue to help us make the France translation awesome!
