### ISSUE TITLE
Menu randomly not showing  up on iPad 

### ISSUE THREAD

**Issue by elsobrino** [elixirschool/elixirschool#2302]
![FA03AB02-B165-409E-94BC-D51C822CCE4F](https://user-images.githubusercontent.com/450369/80638563-e9123700-8a60-11ea-9ba7-b574b627bb9c.png)

**Comment by thiamsantos** [comment]
I'm also experiecing this behaviour. It seems to happen in all mobile layouts.

I was not able to understand why, but seems that sometime the `is-loading` class is not removed from the `body`

After the page finished loading the `is-loading` class is still there.
![image](https://user-images.githubusercontent.com/13632762/82814712-08d52900-9e6e-11ea-9b18-a433fa7e3f34.png)

For some reason this line is not been executed https://github.com/elixirschool/elixirschool/blob/0f08b43efbfa0406fe93c03a9e82b650e4373894/_assets/javascripts/main.js#L46. This caused the sidebar to remain hidden https://github.com/elixirschool/elixirschool/blob/c9acdb10175dd406f45327bcc908b18b81fd76ce/_assets/stylesheets/layout/_sidebar.scss#L256.

**Comment by tajchumber** [comment]
hi @elsobrino and @thiamsantos a PR is definitely welcome for this if you have the time! :)
