### ISSUE TITLE
[Suggestion] Translations for blog posts

### ISSUE THREAD

**Issue by thiamsantos** [elixirschool/elixirschool#2315]
We have some real nice blog posts in elixirschool, would be nice if we could also translate this articles.

**Comment by doomspork** [comment]
@SophieDeBenedetto, @gemantzu, and I have been discussing this a bit in the Elixir School slack. I think we all agree that blog posts should not be translated. Managing the lesson translations is difficult enough, adding blog posts on top of that is just too much.

That said there are 2 things that have come from these conversations:

1. Finding a way to encourage people to contribute blogs in other languages. The blog doesn't _have_ to be in English.
2. Expanding our lessons with some of the content from the blogs such as Telemetry and LiveView content.

Thoughts?

**Comment by thiamsantos** [comment]
> Managing the lesson translations is difficult enough, adding blog posts on top of that is just too much.

@doomspork Yeah, makes sense. Is really a lot of work to translate everything.

> Finding a way to encourage people to contribute blogs in other languages. The blog doesn't have to be in English.

That seems to be a really nice approach. Much of the content is made in english, making even more difficult for newcomers that are not english speakers to getting started in the language. Maybe we could share in each regional communities that elixirschool is accepting posts in any language and try to talk with some authors/bloggers to cross post their article here as well.

WDYT?

**Comment by doomspork** [comment]
I'm going to close this for now but I'd very much like to find a way to encourage folks to contribute blog posts in languages other than English. I think the new functionality we're rolling out will make this much easier to accomplish and expose.
