### ISSUE TITLE
Examples reference concepts not yet introduced

### ISSUE THREAD

**Issue by ghost** [elixirschool/elixirschool#2344]
I'm a newcomer to Elixer and moving through the basic concepts sequentially has been a bit confusing as there are a few instances of examples for a given section referencing concepts that are introduced on a later page. 

For example, pipes are used in a code block in lesson **3. Enum** and then in lesson **6. Functions** for examples of **Guards** and **Default Arguments** but are never named or explained until lesson 7. 

I understand that sometimes this is unavoidable but in these cases it should be explicitly noted--there should be either a brief explanation or at least a link to where that functionality is explained. I find myself unable to parse an example and thus not really grasp the concept but not knowing how to find a reference to explain what I'm looking at since I don't know what it is called. It just makes the learning process more frustrating than it needs to be.

I don't mind adding references myself and submitting a pull request if that's a good way to proceed. There are a few other instances besides the example I mentioned and I expect I may find a few more as I moved forward, should those be handled as separate issues or just handled under this one?

**Comment by doomspork** [comment]
Hello @radet5, this is good feedback! We're always looking to make improvements to the content, things like this are great additions.

> I understand that sometimes this is unavoidable but in these cases it should be explicitly noted--there should be either a brief explanation or at least a link to where that functionality is explained. 

Wholeheartedly agree! I think we should get better with callouts for things such in addition to the exercises' we're working on. The existing callouts are too subtle.

> I don't mind adding references myself and submitting a pull request if that's a good way to proceed.

Yes please do open PRs, the more the merrier! I really appreciate you offering to get involved, it's wonderful to have new perspectives! :tada: 

>  There are a few other instances besides the example I mentioned and I expect I may find a few more as I moved forward, should those be handled as separate issues or just handled under this one?

This is tricky. For your sake it is probably easier to do just one but if the changes start to creep up in size, it becomes difficult to get it all reviewed and incorporated sometimes. While more of a pain, smaller PRs are much easier to review and approve.

At the top of every lesson is a version used to help the translators keep up. Adding these changes, we'll need to bump the impacted lessons minor version (major.**minor**.patch).

Let us know if there's anything else we can do to help :grin: Have a great weekend

**Comment by doomspork** [comment]
Howdy @radet5 I wanted to follow up with you and see if I could be of any help :grin:
