### ISSUE TITLE
Moving Nerves lesson from Advanced section to Specifics section

### ISSUE THREAD

**Issue by ojizero** [elixirschool/elixirschool#2363]
Currently the last lesson in the advanced topics on Elixir is about the [`Nerves`](https://elixirschool.com/en/lessons/advanced/nerves/) framework. It felt very odd transitioning from language specific topics, to jumping on a specific framework, I can only suspect it was done to serve as an example (_maybe?_), but I think it should be moved under the "specifics" section similar to the lessons on Plug, EEx, and ETS?

Any ideas comments on this? Or is there a specific reason I missed on placing that lesson under the advanced section?

**Comment by doomspork** [comment]
This is a good change to me. If we had someone willing to contribute even more Nerves specific material I'd say we could make a Nerves section but for now Specifics seems to be a good home.

**Comment by ojizero** [comment]
@doomspork yea Nerves seems could take it's own section! Sadly I'm by no means qualified 💃 in the mean time I opened a PR moving it over to specifics 🍻
