### ISSUE TITLE
Update `Enum.md` Capture operator section in translated guides

### ISSUE THREAD

**Issue by jersearls** [elixirschool/elixirschool#2382]
PR https://github.com/elixirschool/elixirschool/pull/2377 Adds instruction and examples on the use of the capture operator with the Enum module.

# Translation

Translation progress:

- [x]  en
- [ ]  ru /cc @brain-geek / @nscyclone
- [ ]  ko /cc @devleoper
- [ ]  jp /cc @3100
- [ ]  no /cc @therobinsj
- [ ]  pl /cc @Koziolek
- [ ]  sk /cc @michalvalasek
- [ ]  fr /cc @julienXX
- [ ]  cn /cc @cizixs
- [ ]  es /cc @aleandros / @jonahoffline / @edwinallenz
- [ ]  pt /cc @pragmaticivan
- [ ]  vi /cc @joneslee85
- [ ]  it /cc @lucidstack / @sformisano
- [ ]  my /cc @alkaha
- [ ]  id /cc @rezaprima

**Comment by doomspork** [comment]
@jersearls I love your initiative :+1: For your edification (if you weren't aware and to save you time in the future), we've (read: largely @gemantzu) have addressed the need for these issues with notices on translated lessons:

![image](https://user-images.githubusercontent.com/73386/93900980-41b5cb00-fcb3-11ea-9803-eaf26473146a.png)

In addition to that, each language has a generated "Translation Report":

https://elixirschool.com/es/report/

**Comment by jersearls** [comment]
Oh excellent! I was just following the https://github.com/elixirschool/elixirschool/blob/master/CONTRIBUTING.md guide. Didn't know the process had changed.

**Comment by doomspork** [comment]
Oh! We should update that accordingly. @jersearls would you like to do that? If not I can :grin:

**Comment by jersearls** [comment]
On it.

**Comment by jersearls** [comment]
https://github.com/elixirschool/elixirschool/pull/2384
