### ISSUE TITLE
"Code Copy" button for code snippets

### ISSUE THREAD

**Issue by konung** [elixirschool/elixirschool#2405]
@doomspork  per your suggestion

Related to this code pull https://github.com/elixirschool/elixirschool/pull/2378

--------------

## The problem

When I added "Copy" button to snippets, I realized  Elixir School has two types of code samples.

1. Actual copypaste codez  
  a. *this works fine*
2. Output from shell to illustrate one point or another.  
  a. *when copied, it grabs everything including `iex>` and other misc chars that come from the shell. See screenshots. 

## Suggestions

Separate the two. This would need to be a manual process. Programmatically, they are almost identical. They are wrapped in the same class, and the only difference is `"iex>"`
   1. Change the class name on "console" examples, to remove "Copy" button. 
   2. Remove "iex>" from "console" examples.
       a. this might be easier, as simple search/replace in Text Editor? But prone to errors? The actual output of the commands is often shown as "comments" in situations like these, that I've seen on other websites.

       ```elixir
              # Instead of 
              iex> user = %{first: "doomspork"}
              %{first: "doomspork"}       
              
              # Change to this
              user = %{first: "doomspork"}
              #iex> %{first: "doomspork"}       
       ```
       This approach allows the reader, to simply copy code sample and try it in console, without much hassle. 
       b. And adding some kind of indicator that it's the output from iex for readers? 
       c. Combination of the two? To also visually separate them?
       d. Somewhat related suggestions from Google Devs https://developers.google.com/style/code-syntax
       e. ?

Any suggestions on how to improve this?

![image](https://user-images.githubusercontent.com/72493/94579675-b7cfaa00-023e-11eb-9e13-3f91d289f653.png)
![image](https://user-images.githubusercontent.com/72493/94579693-bb633100-023e-11eb-8a18-f22c3ce80f8d.png)

**Comment by doomspork** [comment]
@elixirschool/developers I would love to get some input on how we can enhance these examples to make them easier to copy.

**Comment by nscyclone** [comment]
I've proposed a [PR to rouge](https://github.com/rouge-ruby/rouge/pull/1601) that should help to resolve the `iex> ` prompt issue. Unfortunately, Ruby is not my strong suit so I'd be glad if someone took a peek at this before the rouge team does so we could save some time if there is something obvious to work on.

**Comment by konung** [comment]
@nscyclone I didn't even know rouge existed :) so you are way ahead of the game there.  Nothing obvious jumps at me, unless there is something specific to the project, that rouge maintainers won't like. 

Thank you!
