### ISSUE TITLE
Refreshing - Visiting pushed content

### ISSUE THREAD

**Issue by gemantzu** [elixirschool/elixirschool#2456]
I am seeing some weird behaviour on the website:
I know I have pushed some PRs in, when I visit the translation report or the page fixed itself, it shows that the changes haven't been implemented. If I hit Ctrl + F5, it shows the corrected page / report.
If I simply refresh the page again, it shows the old one. I have seen this in my Firefox @ PopOS, and in a Safari and Chrome @ the MacOS of a friend.
I am thinking it might have to do with the PWA we have implemented, but I am not entirely sure. Any ideas?

**Comment by doomspork** [comment]
I think this is Cloudflare caching at the boundary. I'm going to close this for now but let's keep an eye on it.
