### ISSUE TITLE
HTML and accessibility issues

### ISSUE THREAD

**Issue by jaimeiniesta** [elixirschool/elixirschool#2490]
Hello all, I've run a site-wide accessibility check on ElixirSchool.com that has scanned 700+ web pages on the site using [Axe Core](https://github.com/dequelabs/axe-core) and [W3C HTML validator](https://validator.w3.org/), and here are the results:

https://rocketvalidator.com/s/3791b569-6b56-4b15-af23-653d18625d72

We can take this issues list as an opportunity to make Elixir School a more accessible site for everyone. Take this report as low-hanging fruit, it's a long list but all the issues are pretty easy to fix.

If we fix these issues, everyone is going to benefit: you don't need to have severe sight issues to have some problem reading the lessons; I'm 47 and use glasses and I need to increase the font size to read the lessons without effort.

I can provide updated reports periodically (disclaimer: Rocket Validator is a product I created and maintain), and if you're interested in running your own reports for open source sites like this one, feel free to contact me at jaime@rocketvalidator.com and I'll set you up for free open source accounts).

**Comment by doomspork** [comment]
Sorry for the delay in getting back to you @jaimeiniesta, I've been overwhelmed with notifications on Github this year :cold_sweat: 

I think this is a _great_ idea. I'm currently in the process of updating the site to use TailwindCSS and Phoenix. I hope these changes will make things easier to maintain and iterate on. Improving the responsiveness of the site along with accessibility would be wonderful to accomplish with this :tada:

**Comment by jaimeiniesta** [comment]
No problem @doomspork ! We're all super busy these days...

Moving to Tailwind and Phoenix is an awesome idea. I recently migrated Rocket Validator to Tailwind and Phoenix LiveView and the results are amazing, the new interface is super responsive.

Here's an updated report - just so you can check the new interface

https://rocketvalidator.com/s/3791b569-6b56-4b15-af23-653d18625d72

I'll be happy to provide free user accounts for open source - if you're interested just ping me at the email above and I'll set you up. It's easy to set up a schedule to check the site periodically, or after deploys.

**Comment by doomspork** [comment]
I'm going to close this since we've moved this work to the new School House repo 👍
