### ISSUE TITLE
Alternative time zone database

### ISSUE THREAD

**Issue by mathieuprog** [elixirschool/elixirschool#2577]
elixirschool suggests to install the Tzdata library for handling time zones. However this library is currently very bugged and may also  crash the application, see [https://elixirforum.com/t/29358](https://elixirforum.com/t/29358)

Two reliable time zone libraries are:

* tz (mine) https://github.com/mathieuprog/tz
* time_zone_info https://github.com/hrzndhrn/time_zone_info

**Comment by doomspork** [comment]
Thanks @mathieuprog! We'll need to go back and review this content and decide how best to proceed. 

I'd really like to avoid linking out to external libraries to avoid issues like this now and in the future. It quickly becomes a burden on the maintainers to keep track of which libraries are being updated, which support the current Elixir version, etc.

**Comment by mathieuprog** [comment]
Maybe you can link here then:
https://hexdocs.pm/elixir/1.12/DateTime.html#module-time-zone-database

**Comment by doomspork** [comment]
Great idea 🎉
