### ISSUE TITLE
One line Function body

### ISSUE THREAD

**Issue by anishcr** [elixirschool/elixirschool#2585]
I am an Elixir newbie and have been going through elixirschool.

in https://elixirschool.com/en/lessons/basics/functions/ , it is mentioned that "If our function body only spans one line, we can shorten it further with do:"

I misunderstood this as if we use "do:", then the "do action" is whatever written after the "do: " till end of the line (or till an ";" or "#" is encountered in that line.

So i was surprised to note that my below code was not working as expected. Instead it was like "do: :rand.uniform(6) |> Enum.sort"

```
   def test1 do
     for _ <- 1..4, do: :rand.uniform(6)
     |> Enum.sort
   end
``` 

I tried the below code and ensured that just using "do:" does not make it a one liner.

```
defmodule MyMacro do
   defmacro __using__(_) do
     quote do
       def fun1, do: [1, 2]
 
         |> Enum.map(&(&1 * &1))
     end
   end
 end
 
 defmodule MyTest do
   use MyMacro
 
   def fun2, do: [3, 4]
 
     |> Enum.map(&(&1 * &1))
 end
```

Maybe including the case of "|>" in the article will help beginners like me to understand the change "|>" brings to a one liner.

**Comment by doomspork** [comment]
Thanks for calling this out @anishcr. I'm not entirely sure how best to address this. In this example we're trying to pipe a function's definition into a pipeline which is not valid Elixir however we don't suggest doing that in any of our content 🤔  I think maybe the best thing is a note when we introduce pipelines that they can only work with function calls, not definitions.
