### ISSUE TITLE
Blog: Clean Control Flow in Elixir with Pattern Matching and Immutability

### ISSUE THREAD

**Issue by cristineguadelupe** [elixirschool/elixirschool#2586]
As a suggestion from @SophieDeBenedetto, my goal with this post is to show how we can use pattern matching instead of guard clauses to implement a really clean control flow in Elixir.

**Comment by SophieDeBenedetto** [comment]
Thanks for opening this issue @cristineguadelupe! I've already seen your draft and am excited to get this post published 🚀 
Whenever you're ready, go ahead and fork this repo and open a PR with your post under this directory https://github.com/elixirschool/elixirschool/tree/master/_posts and we'll get it reviewed from there 😄
