### ISSUE TITLE
New Lesson Ideas

### ISSUE THREAD

**Issue by doomspork** [elixirschool/elixirschool#2604]
- [ ] Internationalization / gettext  (see #2269)
- [ ] Broadway
- [ ] Flow
- [ ] Cachex
- [ ] Redix
- [ ] Advanced Ecto Querying

**Comment by kipcole9** [comment]
Very happy to collaborate on I18n/L10n from #2269 (I'm the author of [Elixir CLDR](https://github.com/elixir-cldr).

**Comment by AdrielBento** [comment]
Does it make sense to create a category just about communication protocols and frameworks, like absinthe for GraphQL or elixir-grpc for GRPC?

**Comment by doomspork** [comment]
@AdrielBento I think so, I just don't know exactly where those would fit in. We are trying to organize lessons better on the new site we're preparing to roll out: http://beta.elixirschool.com/

I'd love to capture things like Protobuf, gRPC, and others. They're very useful and are growing increasingly common for applications in this ecosystem.

**Comment by J0** [comment]
Hey,

Thanks for putting this together. Can I check what would be the process for taking up a topic listed above(say Cachix or Broadway)?

Lmk!
