### ISSUE TITLE
Bug in Chrome App

### ISSUE THREAD

**Issue by mojo706** [elixirschool/elixirschool#2609]
👋🏾  Not sure this is the place to put this or if it even needs to be an issue. The toggle theme button doesn't work well on the Chrome App. Toggling the theme results in a blank page. Only way to fix that is to reinstall the app with your desired theme already set on the web app. See attached image.

<img width="1217" alt="Screenshot 2021-06-30 at 04 13 39" src="https://user-images.githubusercontent.com/908380/123887172-ad6f4780-d959-11eb-9b3d-97bc66d4e74d.png">

It doesn't matter if you're toggling between the lighter or darker theme.

**Comment by doomspork** [comment]
@mojo706 Apologizes that I missed this report. Can you see if this issue still remains now that the new site has been fully rolled out and the caching issues resolved?
