### ISSUE TITLE
Date & Time links 404

### ISSUE THREAD

**Issue by devtayls** [elixirschool/elixirschool#2654]
https://elixirschool.com/en/lessons/basics/date-time/

Returns 

![image](https://user-images.githubusercontent.com/16793430/134683406-679714f6-b4c3-412e-9d74-d6294ebcba9c.png)

**Comment by devtayls** [comment]
I think I'd like to help with this one

Can someone give me a primer on routing in the project?

**Comment by doomspork** [comment]
If you navigate back to elixirschool.com and do a hard browser refresh, do you see a new site?

**Comment by devtayls** [comment]
Yes. Looks like my cache was really outta date!

**Comment by devtayls** [comment]
Date and Time now resolve. 

Thanks!

**Comment by doomspork** [comment]
Sorry about that! I'm working to sort out why the cache is still serving the old site to a number of visitors
