### ISSUE TITLE
Titles in Lessons dropdown are not tranlasted to the current language

### ISSUE THREAD

**Issue by eksperimental** [elixirschool/elixirschool#2753]
The titles have already been translated.
https://elixirschool.com/es/lessons/advanced/umbrella_projects

![image](https://user-images.githubusercontent.com/9133420/149668070-dea502b7-83a8-4e61-aee5-87414f1cdef3.png)

**Comment by kinson** [comment]
Thanks for opening this issue, we currently have a ticket open in the school_house repo to address this: https://github.com/elixirschool/school_house/issues/154

If you want to take a stab at implementing this that would be awesome! If you do, let me know if you have any questions!

**Comment by eksperimental** [comment]
Thank your for your answer.
Feel free to close this one if you consider it appropiate
