### ISSUE TITLE
Pipe operator used before it's introduced

### ISSUE THREAD

**Issue by snus-kin** [elixirschool/elixirschool#2788]
Hi,

Nothing major, just reading through the lessons and the pipe operator is used in examples on the functions page before it's introduced by the next page, kind of just breaks the flow is all in my opinion. 

[Functions Lesson](https://elixirschool.com/en/lessons/basics/functions)

**Comment by allefgomes** [comment]
Yeah! You are right.
I saw that in [guards session](https://elixirschool.com/en/lessons/basics/functions#guards-6) the pipe operator appear and don't have a previews explanation about it.

The sessions that use pipe operator are:
[Guards](https://elixirschool.com/en/lessons/basics/functions#guards-6) 
[Default Arguments](https://elixirschool.com/en/lessons/basics/functions#default-arguments-7)

I think that we have two options:
1. We can put a simple signification like "The pipe operator `|>` is to send the result of function A to function B as the first argument. You will understood more about pipe operator in the next lesson" .
2. The Guards and Default Arguments sessions can be after introduction of pipe operator.

**Comment by snus-kin** [comment]
Personally (and as someone who is not familiar with Elixir) it seems like a fairly important part of the language's syntax. Perhaps something could be mentioned (as to the effect of option 1) in the first chapter? 

From the Pipe Operator page:
"The pipe operator |> passes the result of an expression as the first parameter of another expression." 

This seems like a fairly simple and intuitive explanation that could be included, perhaps then reference there is more detail in the dedicated chapter to it.

**Comment by allefgomes** [comment]
@doomspork can you close this issue?
It was finally at #2799

**Comment by doomspork** [comment]
Done, thank you again @allefgomes!

**Comment by doomspork** [comment]
@allefgomes we should backport this change to the other languages. Would you like to do that? If not I'm happy to do so.

**Comment by allefgomes** [comment]
> @allefgomes we should backport this change to the other languages. Would you like to do that? If not I'm happy to do so.

I can do it in the next week :)
