### ISSUE TITLE
cross-post of a blog

### ISSUE THREAD

**Issue by TraceyOnim** [elixirschool/elixirschool#2817]
Is it okay to do a cross-post of a blog i.e can I post the same blog here in Elixirschool and also in medium?

**Comment by doomspork** [comment]
Howdy @TraceyOnim! I think we _should_ open up the door to more cross posts so long as they align with our mission to provide Elixir content for everyone. Thanks for reaching out to check with us on this, really appreciate 🙏 

We could potentially expand some of our functionality to better support cross post blogs too. I'll think about that a bit more 🤔  cc @burden @kinson

**Comment by doomspork** [comment]
Closing for now because I believe we answered the question. Cross posted blogs are welcome and if the occurrence of them picks up, we'll expand our functionality around cross posting.
