### ISSUE TITLE
Merge Translated PRs Automatically After Review Period

### ISSUE THREAD

**Issue by kinson** [elixirschool/elixirschool#2834]
@kinson @btkostner do you think it's feasible to build a GHA to merge translated PRs after _N_ days if there's no review from the team?

_Originally posted by @doomspork in https://github.com/elixirschool/elixirschool/issues/2827#issuecomment-1214147967_

**Comment by btkostner** [comment]
Should be feasible. Though we will probably need a robot user account with special permissions

**Comment by blum675** [comment]
Thank you. Speaking of this, I also want to share a good online essay writing service. An essay is a written piece of work that typically explores a specific [Read about The Best Essay Writing Service 2022](https://www.clevescene.com/sponsored/the-best-essay-writing-service-2022-independent-review-39279903) topic, presents an argument or viewpoint, and provides supporting evidence or analysis. Essays come in various forms, including argumentative, descriptive, narrative, and expository, and are a common assignment in education to develop critical thinking and communication skills.
