### ISSUE TITLE
[JA] Merged PR is not reflected

### ISSUE THREAD

**Issue by nako-9h-sleep** [elixirschool/elixirschool#2871]
Thanks for merging my pull request.
https://github.com/elixirschool/elixirschool/pull/2870

It looks like the deployment process was executed in github actions, but I could not confirm the reflection.
https://elixirschool.com/ja/lessons/basics/pattern_matching

Do I need to follow any other procedures?

**Comment by doomspork** [comment]
@nako-9h-sleep this should have been fixed, there were some issues sometime ago with deployments but they were fixed.
