### ISSUE TITLE
Portuguese Translations

### ISSUE THREAD

**Issue by pragmaticivan** [elixirschool/elixirschool#355]
## Get Involved!

We are seeking **Portuguese** translators for this project. If you would like to get involved with translating a lesson. Please folk the project and start translating.
- **Set up**
  - [x] _config.yml
  - [x] index.md 
- **Basics**
  - [x] Basics 
  - [x] Collections
  - [x] Enum
  - [x] Pattern Matching 
  - [x] Control Structures 
  - [x] Functions 
  - [x] Pipe Operator
  - [x] Modules 
  - [x] Mix
  - [x] Sigils
  - [x] Documentation 
  - [x] Testing
  - [x] Comprehensions
  - [x] Strings  
  - [x] Custom Mix Tasks
  - [x] IEx Helpers 
- **Advanced**
  - [x] Erlang Interoperability
  - [x] Error Handling
  - [x] Executables
  - [x] Concurrency
  - [x] OTP Concurrency
  - [x] OTP Supervisors
  - [x] Metaprogramming
  - [x] Umbrella Projects
  - [ ] Specifications and types
  - [ ] Behaviors
  - [ ] GenStage
  - [x] Protocols
- **Specifics**
  - [x]  Plug
  - [x]  Ecto
  - [x]  Embedded Elixir (EEx)
  - [x]  Erlang Term Storage (ETS)
  - [x]  Mnesia
  - [x]  Debugging
- **Libraries**
  - [ ]  Guardian
  - [x]  Poolboy

**Note**
Those new to Elixir and / or Github are encouraged to get involved :smile:. 1 [Pull Request](https://help.github.com/articles/using-pull-requests/) per lesson.

**Comment by doomspork** [comment]
@pragmaticivan Do you still find this particular Issue format helpful? I'm looking for ways to handle PRs like #452, any thoughts would be greatly appreciated.  I'd like to refrain from using a third-party service if possible, those seem to bring about their own unique headaches

**Comment by pragmaticivan** [comment]
Not really for new changes. Can't see a better way unless we have inside the wiki explaining that if someone create a new change they chould report the issue for all the languages available.

**Comment by capaci** [comment]
Can I make "Custom Mix Tasks" translation? :)

**Comment by capaci** [comment]
Can I make Custom Mix Tasks translation? :)

**Comment by capaci** [comment]
I did it on PR #725

**Comment by norbajunior** [comment]
Hey guys. I'm going to translate the IEx Helpers.

**Comment by rrmartins** [comment]
Hey guys, we have some page to translate?

**Comment by rrmartins** [comment]
Can I make Debugging translation?

**Comment by pragmaticivan** [comment]
Hey @rrmartins if you check this link: https://github.com/doomspork/elixir-school/issues?q=is%3Aissue+is%3Aopen+label%3Atranslation

There are many variations of the current files, maybe you can help to keep all the content updated.

**Comment by rrmartins** [comment]
Hey @pragmaticivan, ok,  I saw that we do not have a translation for Debugging page in Portuguese. Can you do this translation? :)

**Comment by pragmaticivan** [comment]
Sure you can @rrmartins, go for! :D Thanks!

**Comment by pragmaticivan** [comment]
List updated :)

**Comment by vicdda** [comment]
Hey, i have done the translation of the lesson of types and specifications.

**Comment by pragmaticivan** [comment]
Thanks @vicdda I will start reviewing soon.

**Comment by guilhermelazzari** [comment]
I'll take GenState.

**Comment by doomspork** [comment]
Wonderful, thank you @guilhermelazzari!!

**Comment by guilhermelazzari** [comment]
Hi @doomspork I'll translate Behaviours too.

**Comment by eksperimental** [comment]
I have checked the missing lessons and it is all complete, closing this ISSUE in favour of https://github.com/elixirschool/elixirschool/issues/1295
