### ISSUE TITLE
Probably missed description in Ecto.counting section

### ISSUE THREAD

**Issue by Koziolek** [elixirschool/elixirschool#366]
In lesson about Ecto in section `Counting` we have some code only. Maybe we need some small description like:

```
If we want to count number users that has confirmed account we could use `count/2`:
```

Changes made to the original lesson could be found [here](https://github.com/doomspork/elixir-school/pull/401/files).
## Translation

Translation progress:
- [x] en
- [x]  ru /cc @nscyclone
- [x]  ko /cc @devleoper
- [x]  jp /cc @3100
- [ ]  no /cc @therobinsj
- [x]  pl /cc @Koziolek
- [ ]  sk /cc @michalvalasek
- [ ]  fr /cc @julienXX
- [x]  cn /cc @cizixs
- [ ]  es /cc @aleandros / @jonahoffline / @eze1981
- [ ]  pt /cc @pragmaticivan
- [ ]  vi /cc @joneslee85
- [ ]  it /cc @apeacox / @sformisano
- [ ]  my /cc @alkaha
- [ ]  id /cc @rezaprima

**Comment by nscyclone** [comment]
I'll take care of updating the Russian translation.

**Comment by doomspork** [comment]
@Koziolek could you open a PR for English & Polish?  We'll use that to get the other translations completed. 👍

**Comment by nscyclone** [comment]
@Koziolek, how do you look on updating this issue with [this](https://github.com/doomspork/elixir-school/issues/598) format? `en`, `ru` and `pl` translations are already completed.

**Comment by Koziolek** [comment]
It's OK for me :)

**Comment by hinamiyagk** [comment]
Japanese translation is done(#444)

**Comment by cizixs** [comment]
Chinese translation is done at #748.
