### ISSUE TITLE
Updates to Basic's Atom section

### ISSUE THREAD

**Issue by doomspork** [elixirschool/elixirschool#480]
It would be great to incorporate the additions from #470 into the other languages.

Translation progress:
- [x] en
- [x] ru /cc @brain-geek / @nscyclone
- [x] ko /cc @devleoper 
- [x] jp /cc @3100 
- [ ] no /cc @therobinsj 
- [x] pl /cc @Koziolek 
- [ ] sk /cc @michalvalasek 
- [ ] fr /cc @julienXX
- [x] cn /cc @cizixs 
- [ ] es /cc @aleandros 
- [ ] pt /cc @pragmaticivan 
- [ ] vi /cc @joneslee85 
- [ ] it /cc @lucidstack 
- [ ] my /cc @alkaha
- [ ] id /cc @rezaprima

**Comment by doomspork** [comment]
If this format doesn't work for folks, let me know what might work better.  Thank you! 👍

**Comment by Koziolek** [comment]
Done

**Comment by christiansakai** [comment]
@doomspork I can help for id translation if @rezaprima doesn't mind.

**Comment by doomspork** [comment]
@christiansakai all contributions are welcome! 😀
