### ISSUE TITLE
Translate section on updating/accessing maps

### ISSUE THREAD

**Issue by doomspork** [elixirschool/elixirschool#481]
Add section on updating and accessing maps with atoms #452 

Translation progress:
- [x] en
- [x] ru /cc @brain-geek / @nscyclone 
- [x] ko /cc @devleoper 
- [ ] jp /cc @3100 
- [ ] no /cc @therobinsj 
- [x] pl /cc @Koziolek 
- [ ] sk /cc @michalvalasek 
- [ ] fr /cc @julienXX
- [x] cn /cc @cizixs 
- [ ] es /cc @aleandros 
- [ ] pt /cc @pragmaticivan 
- [ ] vi /cc @joneslee85 
- [ ] it /cc @lucidstack 
- [ ] my /cc @alkaha
- [ ] id /cc @rezaprima

**Comment by Koziolek** [comment]
done

**Comment by anderkonzen** [comment]
Gonna take the PT translation
