### ISSUE TITLE
Mention that GenEvent handlers runs in a single process in a single synchronous loop

### ISSUE THREAD

**Issue by heri16** [elixirschool/elixirschool#487]
I think it is good to mention that GenEvent handlers are run sequentially in a single process/pid, and that this will eventually become a bottleneck. The better example would be to dispatch a message from the event_handler to another Process. For example, using GenServer.cast(main_handling_pid, event) for concurrency.

Additionally, If backpressure is desired to prevent overloading Handler GenServer mailboxes, then use GenEvent.ack_notify, together with GenServer.call. All of this is a stop-gap measure to avoid bad OTP patterns until GenBroker is released.

**Comment by doomspork** [comment]
@heri16 would you be open to updating the lesson?

**Comment by brain-geek** [comment]
Solved in #1458

**Comment by heri16** [comment]
Thanks @brain-geek !
