### ISSUE TITLE
Japanese Translations Updates

### ISSUE THREAD

**Issue by doomspork** [elixirschool/elixirschool#49]
# Basics
- [x] Modules (`Compositions` are added) #447 
- [x] Sigils #410
- [x] Documentation #448
- [x] Comprehensions #449 
- [x] Strings #428 
- [x] Custom Mix Tasks #532
# Advanced
- [ ] Error Handling
- [x] Umbrella Projects
# Specifics
- [ ] Embedded Elixir
- [ ] Mnesia

**Comment by doomspork** [comment]
Hi @3100, would you be open to translating the latest lessons into Japanese?

**Comment by 3100** [comment]
I am sorry that I was busy in recent weeks. 
Now I work with some new lessons in [49-japanese-translations-updates](https://github.com/doomspork/elixir-school/tree/49-japanese-translations-updates).

**Comment by doomspork** [comment]
Hey @3100!  No need to apologize, I figured you were busy.  Hope you are well, thanks again for the help :grinning:

**Comment by 3100** [comment]
I updated the TODO list above.

Note
Those new to Elixir and / or Github are encouraged to get involved :smile:. 1 Pull Request per lesson.

**Comment by doomspork** [comment]
Thank you @3100!  I'll try to help by shooting out some tweets this week 👍 

If you've got any ideas send them my way 😀
