### ISSUE TITLE
Update `Enum.chunk_by` in translated guides

### ISSUE THREAD

**Issue by ybur-yug** [elixirschool/elixirschool#529]
PR #528 updated the `Enum.chunk_by/2` section of the basics/enum lesson to be a bit more clear.

You can see the exact changes in English [here](https://github.com/doomspork/elixir-school/pull/528/commits/cdc2d2bec63ab9f7759ee8ba3c0a09ed38f41809).
## Update

**This has since been included to show the arity, see [here](https://github.com/doomspork/elixir-school/compare/master...improvement/add_arity_to_enum_chunk_by_basics#diff-da9b21c2c73f7335cedc97aa18d36b0cR53).**
## Translation

Translation progress:
- [x] en
- [x] ru /cc @brain-geek / @nscyclone
- [x] ko /cc @devleoper 
- [x] jp /cc @3100 
- [ ] no /cc @therobinsj 
- [x] pl /cc @Koziolek 
- [ ] sk /cc @michalvalasek 
- [ ] fr /cc @julienXX
- [x] cn /cc @cizixs 
- [x] es /cc @aleandros / @jonahoffline / @edwinallenz
- [ ] pt /cc @pragmaticivan 
- [ ] vi /cc @joneslee85 
- [ ] it /cc @lucidstack  / @sformisano
- [ ] my /cc @alkaha
- [ ] id /cc @rezaprima

**Comment by nscyclone** [comment]
It seems like `it` is mentioned twice in the task list.

**Comment by ybur-yug** [comment]
@nscyclone woops! Fixing

**Comment by ybur-yug** [comment]
@nscyclone fixed

**Comment by nscyclone** [comment]
I wonder whether we should mention the functions' arities in the [references](https://github.com/doomspork/elixir-school/pull/528/files#diff-da9b21c2c73f7335cedc97aa18d36b0cR53) and [headers](https://github.com/doomspork/elixir-school/pull/528/files#diff-da9b21c2c73f7335cedc97aa18d36b0cR51)? They are used in the [Strings lesson](https://github.com/doomspork/elixir-school/blob/master/lessons/basics/strings.md#length1) and [sometimes in this one](https://github.com/doomspork/elixir-school/blob/master/lessons/basics/enum.md#chunk).
What do you think, @ybur-yug, @doomspork?

**Comment by ybur-yug** [comment]
@nscyclone since its core to the nature of the language itself I think this was an oversight by me. I will update.

**Comment by ybur-yug** [comment]
@nscyclone fixed [here](https://github.com/doomspork/elixir-school/compare/master...improvement/add_arity_to_enum_chunk_by_basics#diff-da9b21c2c73f7335cedc97aa18d36b0cR53) and opening a PR

**Comment by ybur-yug** [comment]
@nscyclone PR opened https://github.com/doomspork/elixir-school/pull/537

**Comment by nscyclone** [comment]
The issue was closed automatically but I suppose it's too early since not all the translations are ready yet.

**Comment by doomspork** [comment]
Good catch @nscyclone!  I didn't notice the magic phrase in that PR that auto-closed this.

**Comment by nscyclone** [comment]
This issue seems to be closed by accident once again.

**Comment by doomspork** [comment]
I suck, sorry @nscyclone!  I need to keep an eye out for those triggers in Github commit messages

**Comment by edwinallenz** [comment]
Sorry it's because I included the `fix #...` keyword in the commit message I'll use `relates to` for feature messages

**Comment by doomspork** [comment]
Thank you @edwinallenz, I'll do my part to be more vigilant with those messages!
