### ISSUE TITLE
Translations style guideline needed

### ISSUE THREAD

**Issue by sformisano** [elixirschool/elixirschool#536]
Hey all,

I was talking with @ybur-yug about helping out with the italian translation of elixir-school when I realised you guys may benefit from a translation style guideline to boot.

i.e. I assume right now it's up to the translator to decide what to do with:
- Source code language, e.g. does `["one", "three", "five"]` become `["uno", "tre", "cinque"]` ?
- Technical terms, e.g. does the translator translate words like `subset` or does he keep them in English since they're part of an established technical jargon that mixes well with the language syntax?

Personally I'm a fan of keeping translations to the minimum and leaving both source code and established technical terms in English, but I'm biased as I'm fluent in English so others may disagree.

Whatever flavour you guys want to pick, I think having a written style guideline that can be referenced when merging contributions will help a lot in keeping translations consistent.

Thoughts?

**Comment by ybur-yug** [comment]
CC @brain-geek @nscyclone @devleoper @3100 @therobinsj @Koziolek @michalvalasek @julienXX @cizixs @aleandros @jonahoffline @pragmaticivan @joneslee85 @apeacox @alkaha @rezaprima
(and any others I may have missed, sorry, was going off the typical translation CC list)

**Comment by devleoper** [comment]
I think having consistent guidelines will help translators, especially when they are in decision to do something or not.

But I'm concerned about some (human) languages that already have their own practices. When the usual practice of some (human) language conflict with our guidelines, It can be even worse for translators.

We should carefully think about these practices and keep guidelines simple.

**Comment by ybur-yug** [comment]
@developer I absolutely agree.

With the amount of subtle inflections/incantations that can come along with the territory from how many languages we support translation into. I.E if this was originally written in Pushkin-style Russian and attempted to translate to English directly, the sheer amount of idiomatic content in the original would be incredibly hard to purvey accurately.

However, I lack the knowledge of someone truly bilingual and instead have at best dabbled in things like Russian and French, and have a tenuous but functional grasp on Spanish.

@sformisano I'd be intrigued to hear your opinion on a possible simple-but-effective approach since you have probably dealt with my weird dialect of english that ranges from stupid made up words to southern colloquialisms that are probably unheard of outside that region of the US normally in a professional capacity for work etc. This 'voice' is certainly present with the vast majority if English contributions since there is such a vast space of dialects unless carefully edited.

Hmm...

**Comment by ybur-yug** [comment]
Felt like help wanted was an inappropriate tag since this is more discussion, and adding to that discussion isn't so much 'help' but already implied ** anal retention intensifies **

**Comment by christiansakai** [comment]
I think having consistent guidelines will help, but simple guidelines as the translation varies between translators.

I'm an ID (Indonesia) native speaker, and EN is my 2nd language. As having lived in the USA for the past 5 years, I have a different approach than @rezaprima in translating (I assume he is still located in Indonesia). It seems that his translation looks more like a word-to-word translation, while I usually take the essence of a sentence/paragraph, and then try to formulate it in native ID without losing the essence.

**Comment by nscyclone** [comment]
In the source code we translate only the comments leaving everything else untouched. For technical terms we have the [glossary](https://github.com/doomspork/elixir-school/blob/master/GLOSSARY.md) and there is a small note about the terms translation process in its header.
The translation should obviously be literary. Ideally, I suppose, when someone will read your translation along with the English lesson he shouldn't be able to clearly decide which one is the original.

**Comment by brain-geek** [comment]
> Source code language
I guess it should stay in English, except for the comments - that's the way we do in Russian right now. It makes maintenance much easier, while all parts required for understanding are translated.

> Technical terms
That's a tough question, but from my experience, non-localized terms read very unnaturally. And the only way is localizing to some extent. 

> I think having consistent guidelines will help, but simple guidelines as the translation vary between translators.
We can suggest a generic approach, but anyway applying each rule will be made by the individual translator. Usually, we don't understand the translation text and can't force it.

> The translation should obviously be literary.
I agree with that but to the extent of being a translation of text - not some separately translated words. Any paragraph needs rephrasing and I personally omit some idioms, where they sound alien to the language.

**Comment by sformisano** [comment]
@ybur-yug with regards to slang and idiomatic expressions, I'd say the best practice possible is to simply keep it to a minimum, so perhaps at least avoid using them consciously so translators don't have to go crazy :*)

@devleoper sure, but I doubt languages have an established standard on how to handle, for example, source code. You are right, however, on raising this point RE technical jargon. French, for example, translates every single foreign word that makes it into common usage, even internationally known words like email (courriel) or computer (ordinateur). Italian, on the other hand, translates close to nothing and has a ton of English words that make it into the commonly spoken language, even more so in technical conversation.

@brain-geek RE applying the style guideline, that's a fair point, but it's easy to review a source code block and see if variables and comments are in the right language depending on what convention you guys end up adopting.

Going with what @nscyclone and @brain-geek  suggested should already be a good starting point. I agree that the rules should be generic enough that they can apply to all languages. All other locale specific concerns should remain with the translator.

If you guys end up drafting the style guideline, I'll be more than happy to provide an italian translation for it.

**Comment by brain-geek** [comment]
@sformisano Just a side note - I don't think that this policy/guideline should be translated. It will get out-of-date fast, just adding maintenance costs. And anyway, if someone is translating from english - this person definitely can read that english document.

**Comment by sformisano** [comment]
@brain-geek fair enough :)

**Comment by doomspork** [comment]
We have a rough guide in the Wiki which seems to be doing the trick for now 👍
