### ISSUE TITLE
Fix best practices example in `basics\pipe-operator` translated guides

### ISSUE THREAD

**Issue by eze1981** [elixirschool/elixirschool#574]
PR #569  Fix best practices example in the `basics\pipe-operator` lesson.

You can see the exact changes in English [here](https://github.com/doomspork/elixir-school/pull/569/files#diff-eaff4de352ee1fd132c689fc5651b5d5).
## Translation

Translation progress:
- [x] en
- [x]  ru /cc @brain-geek / @nscyclone
- [x]  ko /cc @devleoper
- [x]  jp /cc @3100
- [ ]  no /cc @therobinsj
- [x]  pl /cc Koziolek
- [x]  sk /cc @michalvalasek
- [x]  fr /cc @julienXX
- [x]  cn /cc @cizixs
- [x]  es /cc @aleandros / @jonahoffline / @eze1981
- [x]  pt /cc @pragmaticivan
- [ ]  vi /cc @joneslee85
- [x]  it /cc @lucidstack  / @sformisano
- [ ]  my /cc @alkaha
- [ ]  id /cc @rezaprima

**Comment by julienXX** [comment]
@eze1981 here is the French update:

## Bonnes pratiques

Si l'arité d'une fonction et supérieure à 1, assurez vous d'utiliser des parenthèses. Ce n'est pas nécessaire pour Elixir mais plus pour les autres développeurs qui pourraient mal interpréter votre code. Si on prends notre 3ème exemple, et enlevons les parenthèses de `String.ends_with?/2`, nous pouvons voir l'avertissement suivant:

```shell
iex> "elixir" |> String.ends_with? "ixir"
warning: parentheses are required when piping into a function call. For example:

foo 1 |> bar 2 |> baz 3

is ambiguous and should be written as

foo(1) |> bar(2) |> baz(3)

true
```

**Comment by Koziolek** [comment]
[PL] done
