### ISSUE TITLE
Description of `use` macro lacks context

### ISSUE THREAD

**Issue by scouten** [elixirschool/elixirschool#585]
http://elixirschool.com/lessons/basics/modules/#use provides a fairly technical description of _what_ `use` does, but doesn't explain _why_ you would use it. Also it refers to the concept of "macro" which I don't yet understand.

**Comment by Koziolek** [comment]
Will be fix in scope of #587

**Comment by brain-geek** [comment]
I think this should be closed, as changes are already implemented and merged in #686 . 

Fell free to reopen it if it's still an issue.
