### ISSUE TITLE
Description of import and require should explain why you use one vs the other

### ISSUE THREAD

**Issue by scouten** [elixirschool/elixirschool#586]
After reading http://elixirschool.com/lessons/basics/modules/#import and http://elixirschool.com/lessons/basics/modules/#require, I don't really understand _why_ I would choose one over the other.

**Comment by scouten** [comment]
BTW, I am overall _very_ impressed with elixir-school. Please take my issues and PRs as suggestions for how to improve something that is already very effective at its mission. I'm very new to Elixir and I'm finding this to be one of the fastest ways to grok the language. :+1:

**Comment by doomspork** [comment]
@scouten thank you for all of your generous feedback!  I _very_ much appreciate it, it's through involvement like your's we are able to improve the resource for everyone!

**Comment by brain-geek** [comment]
I believe that #1461 addressed this issue fully.
