### ISSUE TITLE
Fix description of UTF-8 encoding

### ISSUE THREAD

**Issue by nscyclone** [elixirschool/elixirschool#598]
Changes made to the original lesson could be found [here](https://github.com/doomspork/elixir-school/pull/597/files).
## Translation

Translation progress:
- [x] en
- [x]  ru /cc @nscyclone
- [x]  ko /cc @devleoper
- [x]  jp /cc @3100
- [ ]  no /cc @therobinsj
- [x]  pl /cc @Koziolek
- [x]  sk /cc @michalvalasek
- [ ]  fr /cc @julienXX
- [ ]  cn /cc @cizixs
- [ ]  es /cc @aleandros / @jonahoffline / @eze1981
- [ ]  pt /cc @pragmaticivan
- [ ]  vi /cc @joneslee85
- [ ]  it /cc @lucidstack  / @sformisano
- [ ]  my /cc @alkaha
- [ ]  id /cc @rezaprima

**Comment by julienXX** [comment]
FYI Basic/Strings lesson is not yet translated in French.

**Comment by doomspork** [comment]
Thanks for the heads up @julienXX
