### ISSUE TITLE
Using proper term in 'collection' - cons operator

### ISSUE THREAD

**Issue by brain-geek** [elixirschool/elixirschool#608]
Changes made to the original lesson could be found in #605 .
## Translation

Translation progress:
- [x] en
- [x]  ru /cc @nscyclone
- [x]  ko /cc @devleoper
- [x]  jp /cc @3100
- [x]  no /cc @therobinsj
- [x]  pl /cc @Koziolek
- [x]  sk /cc @michalvalasek
- [ ]  fr /cc @julienXX
- [x]  cn /cc @cizixs
- [x]  es /cc @aleandros / @jonahoffline / @eze1981
- [x]  pt /cc @pragmaticivan
- [ ]  vi /cc @joneslee85
- [ ]  it /cc @lucidstack  / @sformisano
- [ ]  ms /cc @alkaha
- [ ]  id /cc @rezaprima

**Comment by Koziolek** [comment]
Done :)

**Comment by brain-geek** [comment]
Thanks, @Koziolek !
