### ISSUE TITLE
Lesson about ExUnit

### ISSUE THREAD

**Issue by pjhampton** [elixirschool/elixirschool#624]
In the slack convo with @doomspork we discussed the possibility of ExUnit lesson. I will take this forward and keep everyone update in this Github Issue.

**Comment by holsky** [comment]
@pjhampton are you making progress on this? If not, I will look into ExUnit soon so I could write a lesson from a fresh beginner's perspective :)

**Comment by pjhampton** [comment]
Hey @holsky,

Thanks for reaching out! Actually, I have only done the planning and not started it. If it's cool with @doomspork, I think you should definitely give it a go! I have plenty of other stuff to write for the site :-)

**Comment by doomspork** [comment]
Go for it @holsky!

**Comment by holsky** [comment]
Can you invite me to that Slack channel? I think I need to know more about what you think needs to be improved in the current Testing lesson :)

**Comment by doomspork** [comment]
@holsky are you on Elixir Slack?  Our channel is public: #elixirschool

**Comment by pjhampton** [comment]
Anything cookin' here? 🍳

**Comment by doomspork** [comment]
@pjhampton I don't believe so!  Are you ready to dust off your Elixir skills and update the lesson?  😀

**Comment by pjhampton** [comment]
Yep, sounds good to me @doomspork 😄 
Will aim to have it completed by the 31/Mar

**Comment by pjhampton** [comment]
Well 31/Mar didn't happen 🤣 
It seems that a unit on testing was implemented over the past two months on Testing by @eksperimental. Does anybody believe there is value in creating a dedicated lesson for ExUnit now?

**Comment by doomspork** [comment]
We could consolidate our previous testing commentary into an ExUnit test where we can cover some additional topics like mocking in Elixir (or how to not mock).  

I feel like a dedicated lesson would also be a good opportunity to discuss a tool like `bypass` but that breaks the convention of sticking with official packages only for lessons outside of `Library`.  Maybe a bypass lesson could be a short addition to the ExUnit lessons.

Thoughts @pjhampton / @ybur-yug / @nscyclone?

**Comment by pjhampton** [comment]
Woah, looks like I'm only a year and a bit late 😆 
For sure, this would be a good way of coming back to the project!

**Comment by gemantzu** [comment]
I think this would be a great opportunity on a first take on projects (and how to tdd one with ExUnit). Opinions?

**Comment by eksperimental** [comment]
Unit tests are so common and important that they definitely neednto have a lesson, IMO

**Comment by doomspork** [comment]
@gemantzu I'm not sure that would fit well within the Elixir School lessons _but_ that could make for a good series of blog posts outlining how to plan, design, develop, and test an Elixir application.

**Comment by pjhampton** [comment]
It looks like there is an exunit lesson here already: https://elixirschool.com/en/lessons/basics/testing/ 
I hadn't realized. @doomspork should we close this or do you have other ideas?

**Comment by doomspork** [comment]
We can close this until we deem it necessary to expand on it 👍
