### ISSUE TITLE
Update Concurrency section

### ISSUE THREAD

**Issue by doomspork** [elixirschool/elixirschool#667]
PR #665 updated the Concurrency lesson to include recursion in the example and a note about handling multiple messages.
## Translation

Translation progress:
- [x] en
- [x]  ru /cc @brain-geek / @nscyclone
- [x]  ko /cc @devleoper
- [x]  jp /cc @3100
- [ ]  no /cc @therobinsj
- [x]  pl /cc @Koziolek
- [ ]  sk /cc @michalvalasek
- [ ]  fr /cc @julienXX
- [x]  cn /cc @cizixs
- [ ]  es /cc @aleandros / @jonahoffline / @eze1981
- [ ]  pt /cc @pragmaticivan
- [ ]  vi /cc @joneslee85
- [ ]  it /cc @lucidstack  / @sformisano
- [ ]  my /cc @alkaha
- [ ]  id /cc @rezaprima

**Comment by cizixs** [comment]
Chinese version is merged.

**Comment by doomspork** [comment]
Thank you @cizixs, your help is very much appreciated!
