### ISSUE TITLE
Bulgarian Translation

### ISSUE THREAD

**Issue by AgIt0** [elixirschool/elixirschool#691]
Hey, I started looking into the Bulgarian translation, but saw missing lessons and some missed updates from the English lessons, so here's a list of the stuff that need to be tackled:
- Check for errors/missing updates
  - [x] index.md
  - basics
  - [x] basics
  - [x] collections
  - [x] control-structures
  - [x] enum
  - [x] functions
  - [x] pattern-matching
  - [x] pipe-operator
- Translate
  - basics
    - [ ] comprehensions
    - [x] documentation
    - [x] mix-tasks
    - [x] mix
    - [ ] modules
    - [ ] sigils
    - [ ] strings
    - [ ] testing
  - advanced
    - [ ] concurrency
    - [ ] erlang
    - [ ] error-handling
    - [ ] escripts
    - [ ] metaprogramming
    - [ ] otp-concurrency
    - [ ] otp-supervisors
    - [ ] typespec
    - [ ] umbrella-projects
  - specifics
    - [ ] ecto
    - [ ] eex
    - [ ] ets
    - [ ] mnesia
    - [ ] plug

**Comment by AgIt0** [comment]
@doomspork would you assign me? Me and a friend will try to work on this :)

**Comment by doomspork** [comment]
Howdy @AgIt0!  To add you I'll need to make you a contributor.  My only request is that you refrain from pushing directly to master and rely on pull requests instead.  Does that sound good?

**Comment by AgIt0** [comment]
ah I totally forgot about that...sure I won't even push to this repo :) will use the fork anyway

**Comment by doomspork** [comment]
You've been added, welcome to the club 🎉
