### ISSUE TITLE
Clarify simple_one_for_one strategy for Supervisor in translations

### ISSUE THREAD

**Issue by ybur-yug** [elixirschool/elixirschool#700]
PR #695 updated the section on Supervisors to include some additional notes, we should update the translations to include these changes.
## Translation

Translation progress:
- [x] en
- [x]  ru /cc @brain-geek / @nscyclone
- [x]  ko /cc @devleoper
- [ ]  jp /cc @3100
- [ ]  no /cc @therobinsj
- [x]  pl /cc @Koziolek #714 
- [ ]  sk /cc @michalvalasek
- [ ]  fr /cc @julienXX
- [ ]  cn /cc @cizixs
- [ ]  es /cc @aleandros / @jonahoffline / @eze1981
- [ ]  pt /cc @pragmaticivan
- [ ]  vi /cc @joneslee85
- [ ]  it /cc @lucidstack  / @sformisano
- [ ]  my /cc @alkaha
- [ ]  id /cc @rezaprima

**Comment by brain-geek** [comment]
Thanks for creating this one, @ybur-yug !
I'll take russian translation.
