### ISSUE TITLE
Mnesia guide extensions

### ISSUE THREAD

**Issue by doomspork** [elixirschool/elixirschool#711]
PR #697 (thanks @brunogirin!) adds additional content to the mnesia lesson, we'll want to update the translations.
## Translation

Translation progress:
- [x] en
- [x]  ru /cc @brain-geek / @nscyclone
- [x]  ko /cc @devleoper
- [ ]  jp /cc @3100
- [ ]  no /cc @therobinsj
- [x]  pl /cc @Koziolek
- [ ]  sk /cc @michalvalasek
- [ ]  fr /cc @julienXX
- [ ]  cn /cc @cizixs
- [ ]  es /cc @aleandros / @jonahoffline / @eze1981
- [ ]  pt /cc @pragmaticivan
- [ ]  vi /cc @joneslee85
- [ ]  it /cc @lucidstack  / @sformisano
- [ ]  my /cc @alkaha
- [ ]  id /cc @rezaprima

**Comment by anderkonzen** [comment]
I'll take the PT translation for this one
