### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by cizixs** [elixirschool/elixirschool#72]
Hey, I plan to translate the final section into Chinese:
- basics
  - [ ] documentation.md
  - [ ] sigils.md
  - [ ] Custom Mix Tasks
- advanced
  - [ ] errors.md
- specifics
  - [x] etco.md
  - [ ] plug.md
  - [ ] ets.md
  - [ ] eex.md

**Comment by doomspork** [comment]
@cizixs I've added you as a collaborator so you can tag issues and assign yourself to them :+1: 

Let me know if you've got any questions!

**Comment by cizixs** [comment]
@doomspork Cool! This is convenient.

**Comment by doomspork** [comment]
@cizixs I updated this issue so it applies for all Chinese translations, is that okay?  There were a few new lessons.

**Comment by AquarHEAD** [comment]
Hi, just a remind that I'm currently translating the Plug chapter, will submit a PR for review soon :)

**Comment by cizixs** [comment]
@AquarHEAD Glad someone is helping, you go ahead.

**Comment by AquarHEAD** [comment]
Hi @cizixs how about naming "Specifics" to "专章" instead of "详情"? I think the former title describes these chapters as special ones each regarding one thing(library) only, while the latter one sounds more like details, and it feels a bit awkward to use there.

**Comment by cizixs** [comment]
@AquarHEAD "详情" is not very accurate, but I can't find a more appropriate one. "专章" is not a common-used word, can lead to confusion too. 

Change this trasnlation is necessary, just have to come up with another easy-to-understand word.

**Comment by AquarHEAD** [comment]
@cizixs agreed, tried to find some references in translated book but didn't get much luck :(

**Comment by AquarHEAD** [comment]
what about "专题"?

**Comment by cizixs** [comment]
@aquarhead We can settle on "专题" right now. If there comes a better one, we just update it.

**Comment by aquarhead** [comment]
BTW @doomspork I'm not sure where to discuss it, but I think we should add an additional front matter just for marking which commit is the translation based on. So we can use git to compare what has changed between the base commit and current HEAD.

We could even implement some [Jekyll Commands](https://jekyllrb.com/docs/plugins/#commands) to automate generating new translation, and showing git diff between the commit recorded in front matter and current HEAD.

What's your opinion?
