### ISSUE TITLE
Guide about 'require' , 'use' , 'import'

### ISSUE THREAD

**Issue by zmcartor** [elixirschool/elixirschool#742]
The three keywords 'require' , 'use' , 'import' are very close in meaning, but do subtlety different things within Elixir. Especially interested in when to use each, and how to write intelligent 'use' macros.

**Comment by ybur-yug** [comment]
This is [RE this conversation](https://twitter.com/zmcartor/status/788872587363307520) if anyone wants to follow the original bit from twitter.

**Comment by et** [comment]
I'd like to pick this up @ybur-yug and @zmcartor.
Should this be a new lesson or added to an existing section like the [modules](https://elixirschool.com/lessons/basics/modules/) section?

**Comment by doomspork** [comment]
Howdy @et!  That would be great and as far as I know it no one is looking into this one currently.  If you'd like to take a whack at it please do!  

I think we can expand on the modules lesson, what do you think?

**Comment by et** [comment]
Hey @doomspork, I think that seems like the right spot. I'm curious though what would need to be expanded for the [composition section](https://elixirschool.com/lessons/basics/modules/#composition). @zmcartor thoughts?

**Comment by doomspork** [comment]
Not critical but while you're making changes it appears we're missing some backticks in that lesson:

![image](https://cloud.githubusercontent.com/assets/73386/20021241/9fc7fe9c-a29a-11e6-9bf1-85bcaa35a94e.png)

Should be:

"Using `UseImportRequire.UseMe` defines a `use_test/0` function through invocation of the `__using__` macro."

**Comment by notactuallypagemcconnell** [comment]
I think we can close this as its handled in in [composition](https://elixirschool.com/en/lessons/basics/modules/) @doomspork
