### ISSUE TITLE
Translations Update advanced/otp-supervisors.md

### ISSUE THREAD

**Issue by devleoper** [elixirschool/elixirschool#756]
PR #716 Added restart values to the supervisors lesson.
## Translation

Translation progress:
- [x] en
- [x]  ru /cc @nscyclone @brain-geek 
- [x]  ko /cc @devleoper
- [ ]  jp /cc @3100
- [ ]  no /cc @therobinsj 
- [x]  pl /cc @Koziolek 
- [ ]  sk /cc @michalvalasek
- [ ]  fr /cc @julienXX
- [ ]  cn /cc @cizixs
- [ ]  es /cc @aleandros / @jonahoffline / @eze1981
- [ ]  pt /cc @pragmaticivan
- [ ]  vi /cc @joneslee85
- [ ]  it /cc @lucidstack  / @sformisano
- [ ]  my /cc @alkaha
- [ ]  id /cc @rezaprima

**Comment by brain-geek** [comment]
I'm working on the russian version.

**Comment by brain-geek** [comment]
By the way. Thanks, @devleoper for creating this task. For some reason I thought that it's already in place.
