### ISSUE TITLE
GenFlow/Flow Lesson

### ISSUE THREAD

**Issue by ybur-yug** [elixirschool/elixirschool#774]
We need a lesson on Flow/GenFlow to follow up once PR #770 is merged.
It should go through the basics and be a bit short, but emphasize that it is for _large amounts of data_, and not enumerating over a 1000 item list.

**Comment by doomspork** [comment]
We should be sure to cover partitioning, windows, and triggers in addition to the general Flow functionality.

**Comment by yuriibodarev** [comment]
We have a new GenStage lesson so now we will need another one on Flow?

**Comment by ybur-yug** [comment]
Yes @yuriibodarev, feel free to take a stab at it

**Comment by yuriibodarev** [comment]
@ybur-yug Thanks! I wan't to take [RU] translation of GenStage lesson and make a lesson on Flow if possible!

**Comment by doomspork** [comment]
Been over a year so I'm closing this for now.  Still open to new lessons or even blog posts if the content doesn't warrant a whole lesson 😁
