### ISSUE TITLE
Function lesson: Add warning that function headers are matched in order of appearance

### ISSUE THREAD

**Issue by holsky** [elixirschool/elixirschool#798]
One of the things that cost me a lot of time early on, was that I wrote my functions matching in the wrong order, with the broadest pattern on top so that the finer ones below were never reacher. Maybe it would be a good idea to add a small word of warning to the Pattern Matching part of the functions lesson?

**Comment by ybur-yug** [comment]
Can you give some examples of this? I can see it as an issue but have never run into it myself @holsky.

**Comment by doomspork** [comment]
I like this idea @holsky, ordering is important.  Any suggestions on how we might address this?  Would you like to take a stab at adding a note?

**Comment by holsky** [comment]
Will do, probably by end of next week!
