### ISSUE TITLE
Error Handling: Include guidance when to use which type of error handling

### ISSUE THREAD

**Issue by holsky** [elixirschool/elixirschool#799]
While the lesson is great at explaining the mechanism for error handling (including the {:ok, ...}, {:error, ...} convention), I miss some guidance on when to use which type of error handling. I would rephrase the second paragraph like this:

The general conventions for the types of error handling in Elixir go like this:
  * for errors that are part of the normal operation of a function (e.g. a user entered a wrong type of date), a function (example/1) returns {:ok, result} and {:error, reason} accordingly
  * for errors that are not part of normal operations (e.g. being unable to parse configuration data) you throw an exception

Usually you also add a second version of the function with a ! (example!/1) that returns the unwrapped result or raises an error. This lesson will focus on interacting with errors of the latter type.

**Comment by ybur-yug** [comment]
Do you want to take a stab at a PR @holsky?

**Comment by holsky** [comment]
Love to, probably by end of next week.

**Comment by brain-geek** [comment]
@holsky Is it fine that I based off changes fixing this issue on your comment? I noticed that it's been two years since the initial discussion.
