### ISSUE TITLE
Guardian Translation

### ISSUE THREAD

**Issue by ybur-yug** [elixirschool/elixirschool#830]
The new [Guardian Lesson](https://github.com/doomspork/elixir-school/pull/790/files#diff-e538c0f2f91ebba8407d60afed009eed) was just merged today (11/28/16).

PR #790 was the origin.

## Translation

Translation progress:
- [x] en
- [x]  ru - @brain-geek has said he will take up
- [x]  ko /cc @devleoper
- [ ]  jp /cc @3100
- [ ]  no /cc @therobinsj 
- [x]  pl /cc @Koziolek #907 
- [ ]  sk /cc @michalvalasek
- [ ]  fr /cc @julienXX
- [ ]  cn /cc @cizixs
- [ ]  es /cc @aleandros / @jonahoffline / @eze1981
- [ ]  pt /cc @pragmaticivan
- [ ]  vi /cc @joneslee85
- [ ]  it /cc @sformisano
- [ ]  my /cc @alkaha
- [ ]  id /cc @rezaprima
- [x]  gr /cc @gemantzu

**Comment by gemantzu** [comment]
#839 greek
