### ISSUE TITLE
Specifications and types translation

### ISSUE THREAD

**Issue by Koziolek** [elixirschool/elixirschool#850]
The new [Specifications and types](https://github.com/doomspork/elixir-school/commit/1562b32e9b253f4d8aa4edb44fd18d07a4c804a1) is ready.

PR #564 was the origin.

## Translation

Translation progress:
- [x] en - #564 
- [x]  ru - /cc @brain-geek / @nscyclone
- [ ]  ko /cc @devleoper
- [x]  jp /cc @3100 - #638
- [ ]  no /cc @therobinsj 
- [x]  pl /cc @Koziolek 
- [ ]  sk /cc @michalvalasek
- [ ]  fr /cc @julienXX
- [ ]  cn /cc @cizixs
- [ ]  es /cc @aleandros / @jonahoffline / @eze1981
- [ ]  pt /cc @pragmaticivan
- [ ]  vi /cc @joneslee85
- [ ]  it /cc @sformisano
- [ ]  my /cc @alkaha
- [ ]  id /cc @rezaprima
- [x]  gr /cc @gemantzu #629

**Comment by hinamiyagk** [comment]
Japanese translation is already done(#638)

**Comment by gemantzu** [comment]
Greek translation is already done(#629)
