### ISSUE TITLE
Translation of Behaviours lesson

### ISSUE THREAD

**Issue by Koziolek** [elixirschool/elixirschool#855]
The new [Behaviours](https://github.com/doomspork/elixir-school/commit/de6a26fdea0f76fd96de6534396863b4c269fd40) lesson is ready.

PR #710 was the origin.

## Translation

Translation progress:
- [x] en - #710  
- [x]  ru - /cc @brain-geek / @nscyclone #885 
- [ ]  ko /cc @devleoper
- [x]  jp /cc @3100 / #1294
- [ ]  no /cc @therobinsj 
- [x]  pl /cc @Koziolek 
- [ ]  sk /cc @michalvalasek
- [ ]  fr /cc @julienXX
- [ ]  cn /cc @cizixs
- [ ]  es /cc @aleandros / @jonahoffline / @eze1981
- [ ]  pt /cc @pragmaticivan
- [ ]  vi /cc @joneslee85
- [ ]  it /cc @sformisano
- [ ]  my /cc @alkaha
- [ ]  id /cc @rezaprima
- [x]  gr /cc @gemantzu

**Comment by gemantzu** [comment]
#821 for greek

**Comment by Koziolek** [comment]
@gemantzu please mark when ready :)
