### ISSUE TITLE
1.4 Changes for References Involving New Deprecations and/or Features Worth Adding

### ISSUE THREAD

**Issue by ybur-yug** [elixirschool/elixirschool#908]
In 1.4 we have a few new features, a good amount of deprecations, and some general improvements.

With this, we should probably keep current _at least_ with deprecations that are present in 1.4 and also consider potentially adding onto lessons to cover the most useful of the new features.

## Shiny New Stuff
- Date/Time/DateTime/NaiveDateTime comparison, addition, diffs
- Other calendar improvements in general
- Enum.min/max changes, as referenced [here](https://github.com/doomspork/elixir-school/pull/696)
- Improvements to some std lib integer functinos
- New kernel warnings for functions referenced as the same as a variable name without ()
- New Task features with stream
- Various mix improvements
- Autocomplete improvements in iex

## Deprecations
If we reference any of this, we should update the sections:

- [x] `Access.key/1` - no references that I found in a first pass
- [ ] The Behaviour module (callbacks now done directly)
- [x] `Enum.uniq/1` deprecated in favor of `Enum.uniq_by/2` - addressed in #696 
- [ ] `Float.to_charlist/1`, `Float.to_string/1`
- [ ] Warn if variable used as a function call - multiple offenses in a few examples, is problem in generated mixfiles from older versions
- [ ] Cant override private functions
- [x] Deprecate `Set` module - No references that I found in a first pass
- [ ] Remove references to `GenEvent` - See Issue #939

**Comment by doomspork** [comment]
Now that we're on to 1.5 (and soon 1.6) I think this can be closed.
