### ISSUE TITLE
Add support to "edit this page" link

### ISSUE THREAD

**Issue by pragmaticivan** [elixirschool/elixirschool#926]
That would automatically link to the file on Github.

<img width="155" alt="screen shot 2017-01-17 at 8 45 24 pm" src="https://cloud.githubusercontent.com/assets/301291/22051174/e65e404c-dcf5-11e6-8bcc-0681e823eea9.png">

**Comment by ybur-yug** [comment]
@pragmaticivan I dont think this would even really be accurate as a function per what it says, though.

You are not actually editing the page, at most you are proposing a change.

This also would bypass `CONTRIBUTING.md` etc and other resources as a means to start working on the project, possibly creating unneeded issues from things stemming from not reading the basics of how changes are desired to be made.

I am 1,000,000% and 14/2 for new contributors and fostering this community, but I think this functionality would not offer anything per the mission of the project.

**Comment by pragmaticivan** [comment]
Having this feature may not cause any problem, but instead lead people to try to submit changes as Pull Request even for small typos. As you know, contributing markdown is used on Github to show an Alert about reading the CONTRIBUTING file (https://github.com/blog/1184-contributing-guidelines). There's no bypass.

The same way issues for new files doesn't have any explanation about how to contribute with that. The user may or may not read the README.md before submiting something.

**Comment by ybur-yug** [comment]
I did not know about the `CONTRIBUTING` feature, but IMO it still would hurt the signals:noise ratio that we have worked quite hard to maintain to be at a reasonable level while still making the project accessible (which I would say is a success, considering we are touching nearly 30 languages that we are translated to with over 150 contributors, <3 to everyone whose given to this awesome thing).

I would question submissions from someone who has not read a document quite literally titled "READ ME", even if they're shown contribution guidelines if they want to really do something for the project.

That said, its just my two cents and the ultimate authority obviously is with @doomspork.

**Comment by doomspork** [comment]
I'd like to mull this over a bit more.  I certainly like the idea of lowering the barrier to contribute but at the same time I also agree with @ybur-yug's concerns.  I can see with a "Edit This Page" feature folks making single changes at a time, not rolling many up into a pull request, this could create a great deal of work for all contributors.

CC @nscyclone, @brain-geek, @devleoper, @joneslee85, or anyone else — any thoughts on this feature?

**Comment by nscyclone** [comment]
There is a `Fork me on GitHub` ribbon at the top right of every page. It leads to the [repository index](https://github.com/doomspork/elixir-school) making the visitors read both `README` and `CONTRIBUTING` unless they purposely aren't going to read those.
I suppose this is sufficient for someone who would want to contribute.

**Comment by devleoper** [comment]
"Suggest Changes" link can also promote visitors to contribute the project. Github helps the user who wants to edit forking and shows "please read guidelines before going further" when someone tries to make a pull request.

For users who might not read README, We can make a page that covers "starting translation of Elixir School from scratch" (which README mainly covers), and then we can add an "add your language if your language is missing" button to that at the language list of Elixir School. 

As a translator, It may make translators and contributors busier to keep up-to-date with upcoming many small PRs and changes that "edit" or "suggest changes" may promote. :smile:

**Comment by brain-geek** [comment]
I've looked through comments and, apparently, one of the main concerns when adding this feature is low quality of such contributions.

If it's not hard to have - I'd suggest adding this feature (should be just Github link of correct format) and see how it goes. Worst case scenario - we'll remove this feature. Best case - we'll improve quality.

Other option to get feedback about typos could be a system like https://orphus.ru/en/ , though this will raise other concerns - like where to send those notifications.

**Comment by doomspork** [comment]
I think we can incorporate this into #944.  When a version is out-of-date we can have a call-to-action to encourage people to edit the page and make changes.

**Comment by eksperimental** [comment]
I would like to say that this feature would be ideal to submit a small correction, such as a typo or something wrong with the code. That way it will not bypass the CONTRIBUTING file

**Comment by doomspork** [comment]
@pragmaticivan / @eksperimental are either of you interested in implementing this?  If not, let's close the issue for now 👍

**Comment by eksperimental** [comment]
We have something similar in the Elixir website. I can try to copy that here, so if in a month's time this feature is not submitted, please close this issue (if nobody else took implemented this before)

**Comment by doomspork** [comment]
Thank you @eksperimental ❤️

**Comment by eksperimental** [comment]
it will probably take way less cuz it looks easy

**Comment by doomspork** [comment]
Since there's been no movement on this in some time, I'm going to close this issue for now.  A PR is always welcomed 👍
