### ISSUE TITLE
Show who contributed to the page based on commits in one file

### ISSUE THREAD

**Issue by pragmaticivan** [elixirschool/elixirschool#927]
ex: https://webpack.js.org/configuration/entry-context/

<img width="166" alt="screen shot 2017-01-17 at 8 46 11 pm" src="https://cloud.githubusercontent.com/assets/301291/22051186/013a9474-dcf6-11e6-9baf-f5b9aba73b17.png">

**Comment by iboss-ptk** [comment]
So how webpack website has this react component

```js
export default ({contributors}) => {
  if (!contributors.length) {
    return <noscript />;
  }

  return (
    <div className="contributors">
      <div className="contributors__list">
        {
          contributors.map(contributor => (
            <a key={ contributor }
              className="contributor"
              href={ `https://github.com/${contributor}` }>
              <img src={ `https://github.com/${contributor}.png?size=90` } />
              <span className="contributor__name"> {contributor}</span>
            </a>
          ))
        }
      </div>
    </div>
  );
};
```
which turns out that the github username (the `contributor` prop) is being passed down by page attribute and it is done manually like this:
```md
---
title: NamedModulesPlugin
contributors:
  - shaodahong
---

This plugin will cause the relative path of the module to be displayed when [HMR](/guides/hot-module-replacement) is enabled. Suggested for use in development.

```

My question is do we have the way to automatically generate them without explicilty defining them? Like read the file commit log and get the username out of that by hooking jekyll file complilation.

**Comment by doomspork** [comment]
@iboss-ptk that's a great find!  I'm not against us having the contributors hard coded into the page meta data.  I think I could probably throw together a script to go through the repo and populate all the necessary meta data.

Thoughts @pragmaticivan, @ybur-yug, @nscyclone, and others?

**Comment by pragmaticivan** [comment]
I'm not against us having that approach. Sounds good to me, I think it's very cool to be "recognized" by a contribution.

**Comment by doomspork** [comment]
@pragmaticivan do you prefer people having to add themselves to the contributor list in the meta or something like #1186?

**Comment by pragmaticivan** [comment]
@doomspork I actually prefer the approach on #1186 due to rate limit
