### ISSUE TITLE
Are assets from the `_sass` folder actually being used anywhere?

### ISSUE THREAD

**Issue by nscyclone** [elixirschool/elixirschool#996]
I couldn't find any usage of the files from the mentioned folder but I might be missing something.
I removed it in a separate branch and everything seems to be working as usual both on Heroku and locally.
So the question is: can these assets be safely removed? If not, I'd like to know the secret where and what are they used for.
The branch can be found [here](https://github.com/nscyclone/elixir-school/tree/fix/remove-unused-scss). Ready to propose a PR if needed.
/cc @doomspork

**Comment by doomspork** [comment]
That's a good question @nscyclone!  I will take a peek today and see if we're using those resources or not.

I did get a message this morning from Heroku that the automatic deployment failed, I don't know if it's related to the branch you have or not.  I still need to look into that as well.
